#!/usr/bin/env python3
"""
Translation consistency report using lore-glossary.json.

Checks:
  1) Latin-letter runs left inside zh-Hans strings (likely untranslated names).
  2) High-priority English glossary terms still appearing verbatim in Chinese text.

Outputs:
  World/Documentation/translation-glossary-review.md
"""
from __future__ import annotations

import json
import os
import re
from collections import Counter, defaultdict
from typing import Dict, List, Tuple

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
GLOSSARY = os.path.join(ROOT, "Data", "Localization", "lore-glossary.json")
ZH_DIR = os.path.join(ROOT, "Data", "Localization", "zh-Hans")
OUT_MD = os.path.join(ROOT, "Documentation", "translation-glossary-review.md")

# Latin tokens at least 4 chars (skip short artifacts like "br", "mp")
RE_LATIN = re.compile(r"[A-Za-z][A-Za-z\-']{3,}")


def load_zh_pairs() -> List[Tuple[str, str, str]]:
    """List of (file, key, zh_text)."""
    rows: List[Tuple[str, str, str]] = []
    if not os.path.isdir(ZH_DIR):
        return rows
    for fn in sorted(os.listdir(ZH_DIR)):
        if not fn.endswith(".json"):
            continue
        path = os.path.join(ZH_DIR, fn)
        try:
            with open(path, encoding="utf-8") as f:
                d = json.load(f)
        except Exception:
            continue
        for k, v in d.items():
            if isinstance(v, str):
                rows.append((fn, k, v))
    return rows


def main() -> int:
    if not os.path.isfile(GLOSSARY):
        print(f"missing {GLOSSARY}; run build_lore_glossary.py first", flush=True)
        return 1

    with open(GLOSSARY, encoding="utf-8") as f:
        gloss_doc = json.load(f)

    terms = gloss_doc.get("terms") or []
    # Multi-word proper nouns first (more likely to need consistent handling)
    priority_terms: List[str] = []
    for t in terms:
        name = t.get("canonical_en", "")
        if " " in name and t.get("occurrence_count", 0) >= 2:
            priority_terms.append(name)
        if len(priority_terms) >= 120:
            break

    rows = load_zh_pairs()
    latin_counter: Counter = Counter()
    latin_examples: Dict[str, str] = {}

    term_hits: Dict[str, List[str]] = defaultdict(list)

    for fn, key, zh in rows:
        for m in RE_LATIN.finditer(zh):
            tok = m.group(0)
            # Ignore common UI Latin
            if tok.lower() in {"html", "body", "basefont", "center", "right", "left", "color"}:
                continue
            latin_counter[tok] += 1
            if tok not in latin_examples:
                latin_examples[tok] = f"{fn} `{key}`"

        en_path = os.path.join(ROOT, "Data", "Localization", "en", fn)
        if not os.path.isfile(en_path):
            continue
        try:
            with open(en_path, encoding="utf-8") as f:
                en_map = json.load(f)
            en = en_map.get(key, "")
        except Exception:
            continue
        if not isinstance(en, str):
            continue
        for term in priority_terms:
            if term in en and term in zh:
                term_hits[term].append(f"{fn} `{key}`")

    lines = [
        "# Translation review (glossary-assisted)",
        "",
        "Auto-generated by `World/Source/Tools/review_translations_glossary.py`.",
        "",
        "## 1. Latin fragments inside Chinese strings",
        "",
        "These are **ASCII letter runs** left in `zh-Hans` values. Often they are **proper nouns**",
        "that should use one **consistent** Chinese transliteration (see `lore-glossary.md`).",
        "",
    ]

    for tok, cnt in latin_counter.most_common(60):
        ex = latin_examples.get(tok, "")
        lines.append(f"- **`{tok}`** — {cnt}× (example: {ex})")

    lines.extend(
        [
            "",
            "## 2. English glossary phrases still present in Chinese",
            "",
            "For frequent multi-word English terms from the glossary, the **same spelling**",
            "appears in both English and Chinese for these entries. Decide whether to **keep**",
            "(loan name) or **replace** with a fixed Chinese form from your glossary table.",
            "",
        ]
    )

    for term in sorted(term_hits.keys(), key=lambda x: -len(term_hits[x]))[:40]:
        lines.append(f"### `{term}`")
        lines.append("")
        lines.append(f"- Entries where EN and ZH both contain this phrase: **{len(term_hits[term])}**")
        for sample in term_hits[term][:8]:
            lines.append(f"  - {sample}")
        lines.append("")

    lines.extend(
        [
            "## Maintainer workflow",
            "",
            "1. Run `python3 World/Source/Tools/build_lore_glossary.py` after large content changes.",
            "2. Curate `World/Data/Localization/glossary-approved-zh.json` (optional) mapping `canonical_en` → approved zh.",
            "3. Re-run this review script before releases.",
            "",
        ]
    )

    os.makedirs(os.path.dirname(OUT_MD), exist_ok=True)
    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"wrote {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
