#!/usr/bin/env python3
"""Second pass: translate remaining English entries to Traditional Chinese."""

import json, os, unicodedata

source_path = '/Users/forrrest/projects/UO-Memento/ultima-memento/World/Data/Localization/tools-output/cliloc-batches/groups/10-game-text-4.json'
output_path = '/Users/forrrest/projects/UO-Memento/ultima-memento/World/Data/Localization/tools-output/cliloc-batches/responses/response-10-game-text-4.json'

with open(source_path, 'r') as f:
    source = json.load(f)
with open(output_path, 'r') as f:
    output = json.load(f)

def has_chinese(s):
    for c in s:
        try:
            if 'CJK' in unicodedata.name(c):
                return True
        except:
            pass
    return False

# Find untranslated entries
untranslated = []
for k in source:
    v = output.get(k, '')
    if v and not has_chinese(v):
        untranslated.append((k, source[k]))

print(f"Entries to translate: {len(untranslated)}")

# === BULK TRANSLATION MAP ===
# These are keyed by the lowercase version of the English source text

translations = {
    # === "You" messages ===
    "you may not place this item in your bank box.": "你不能將此物品放入你的銀行箱。",
    "you notice the crest of doom on your fallen foe's equipment and decide it may be of some value...": "你注意到倒下的敵人裝備上有末日（Doom）的紋章，並判斷它可能有些價值……",
    "you have turned in ~1_count~ artifacts of doom": "你已繳交了 ~1_COUNT~ 件末日（Doom）神器",
    "you are already bestowed with this title.": "你已經被授予這個稱號。",
    "you carefully apply tincture of silver to the item.  the effects will fade in one hour.": "你仔細地將銀質酊劑塗抹在物品上。效果將在一小時後消退。",
    "you cannot apply tincture of silver to this item.": "你不能對此物品使用銀質酊劑。",
    "you cannot apply tincture of silver to items that are already slayers!": "你不能對已經是殺手屬性的物品使用銀質酊劑！",
    "you cannot alter an item that has been treated with tincture of silver.": "你不能改變已經用銀質酊劑處理過的物品。",
    "you remove a power scroll and put it in your pack.": "你從力量卷軸書中取出一張力量卷軸放入背包。",
    "you add the scroll to your power scroll book.": "你將卷軸加入你的力量卷軸書。",
    "you already have a hunting permit.": "你已經有狩獵許可證了。",
    "you cannot document someone else's kill.": "你不能記錄別人的獵殺。",
    "this hunting permit has already documented a kill.": "此狩獵許可證已記錄過獵殺。",
    "you must be near a steam powered beverage maker to do that.": "你必須靠近蒸汽動力飲料機才能這樣做。",
    "you are not near a steam powered beverage maker.": "你不在蒸汽動力飲料機附近。",
    "you don't have any coffee grounds.": "你沒有任何咖啡粉。",
    "you must wait ~1_minutes~ minutes before you can use this ability.": "你必須等待 ~1_minutes~ 分鐘才能使用此能力。",
    "your target is already at full health, mana and stamina!": "你的目標已經處於滿生命、魔力和體力狀態！",
    "you feel completely rejuvenated!": "你感到完全恢復了活力！",
    "your target has been rejuvenated!": "你的目標已恢復活力！",
    "you feel rejuvenated!": "你感到恢復了活力！",
    "you have already ended your journey on the path of humility.  you must wait before you restart your path.": "你已結束謙遜之路的旅程。你必須等待才能重新開始你的道路。",
    "you have ended your journey on the path of humility.": "你已結束了謙遜之路的旅程。",
    "you must wait before you can once again begin your journey on the path of humility.": "你必須等待才能再次開始你的謙遜之路旅程。",
    "you have begun your journey on the path of humility.  your resists have been debuffed by ~1_debuff~.": "你已開始謙遜之路的旅程。你的抗性被降低了 ~1_DEBUFF~。",
    "you cannot gain more humility.": "你無法獲得更多謙遜。",
    "you have gained in humility.": "你的謙遜提升了。",
    "you have gained a path in humility!": "你在謙遜之路上取得了進展！",
    "you must be at least a seeker of humility to invoke this ability.": "你必須至少是謙遜追尋者才能使用此能力。",
    "you can only embrace your humility on a pet.": "你只能在寵物身上施展謙遜。",
    "you cannot embrace humility on the dead!": "你不能在死者身上施展謙遜！",
    "you have lost some humility.": "你失去了一些謙遜。",
    "this action disturbs the focus necessary to keep your death ray active and it dissipates.": "此動作擾亂了維持死亡射線所需的專注，射線消散了。",
    "your journey on the path of the humble will end in ~1_seconds~ seconds, at that time your resists will be returned to normal.": "你的謙遜之路將在 ~1_SECONDS~ 秒後結束，屆時你的抗性將恢復正常。",
    "you may not wield a weapon and perform this ability.": "你不能在裝備武器時使用此能力。",
    "you must wait before using this ability again.": "你必須等待才能再次使用此能力。",
    "you are already under the effect of this ability.": "你已經處於此能力的效果下。",
    "you have already learned that level of ~1_skillmastery~!": "你已經學會了該等級的 ~1_SkillMastery~！",
    "you may not wield a weapon and use this ability.": "你不能在裝備武器時使用此能力。",
    "you ready yourself to stagger your opponent!": "你準備好擊退你的對手！",
    "you must have a mace weapon equipped to use this ability!": "你必須裝備錘類武器才能使用此能力！",
    "you deliver a staggering blow!": "你發動了擊退攻擊！",
    "you embrace your toughness!": "你擁抱了堅韌！",
    "your next physical attack will be increased by +~1_val~% damage while reducing your victim's physical attack damage by ~2_val~%.<br>mana upkeep cost: ~3_val~.": "你的下一次物理攻擊傷害提高 +~1_VAL~%，同時降低目標的物理攻擊傷害 ~2_VAL~%。<br>魔力維持消耗：~3_VAL~。",
    "you ready yourself to pierce your opponent!": "你準備好穿透你的對手！",
    "you must have a fencing weapon equipped to use this ability!": "你必須裝備刺擊武器才能使用此能力！",
    "you deliver a piercing blow!": "你發動了穿透打擊！",
    "you ready a volley of flaming arrows!": "你準備好一排火焰箭！",
    "you must have an archery weapon to use this ability!": "你必須裝備弓術武器才能使用此能力！",
    "you must have a fencing weapon equipped to use this ability.": "你必須裝備刺擊武器才能使用此能力。",
    "you must have a swordsmanship weapon equipped to use this ability.": "你必須裝備劍術武器才能使用此能力。",
    "you deliver an onslaught of sword strikes!": "你發動了一連串的劍擊！",
    "you cannot transfer ownership of a commanded undead.": "你不能轉移已命令的不死生物的所有權。",
    "you command the undead to follow and protect you.": "你命令不死生物跟隨並保護你。",
    "the undead becomes enraged by your command attempt and attacks you.": "不死生物因你的命令嘗試而憤怒並攻擊你。",
    "you cannot command that!": "你不能命令那個！",
    "you must have a throwing weapon equipped to use this ability.": "你必須裝備投擲武器才能使用此能力。",
    "you ready your shield.": "你準備好你的盾牌。",
    "you bash you target with your shield!": "你用盾牌猛擊你的目標！",
    "you can't summon a reaper there!": "你不能在那裡召喚收割者！",
    "your disarm attempt was blocked!": "你的卸武嘗試被擋下了！",
    "you blocked a disarm attempt!": "你擋下了一次卸武嘗試！",
    "you must have at least ~1_stam_requirement~ stamina to use this ability.": "你必須至少有 ~1_STAM_REQUIREMENT~ 體力才能使用此能力。",
    "you can't hide whilst on a humility hunt": "你在謙遜狩獵期間無法隱藏",
    "you may not use the spirituality virtue while the attunement spell is active.": "你不能在調和法術生效時使用靈性美德。",
    "you may not cast attunement whilst a spirituality shield is active!": "你不能在靈性護盾生效時施放調和！",
    "you may not use the stables while on a humility hunt. to end your hunt say \"lum lum lum\"": "你在謙遜狩獵期間無法使用馬廄。要結束狩獵請說「Lum Lum Lum」",
    "you may not use this while poisoned!": "你中毒時無法使用此功能！",
    "you may not use this with a mortal wound!": "你受到致命傷時無法使用此功能！",
    "you may not use this while mana drained!": "你魔力被吸乾時無法使用此功能！",
    "you may not use this while your mana is diverted!": "你的魔力被轉移時無法使用此功能！",
    "you may not use this while your mana is corrupt!": "你的魔力被腐化時無法使用此功能！",
    "you may not use this while under the effects of confidence!": "你在信心效果下無法使用此功能！",
    "you may not use this while inside a house or on a boat.": "你在房屋內或船上無法使用此功能。",
    "you lack the skill to command this automaton.": "你缺乏命令此自動機的技能。",
    "you do not have enough mana to keep your death ray active.": "你沒有足夠的魔力維持死亡射線。",
    "you must have the time of legends expansion to use this feature.": "你必須擁有傳奇時刻資料片才能使用此功能。",
    "you are now on a humility hunt. for each kill while you forgo the protection of resists, you shall continue on your path to humility.  you may end your hunt by speaking \"lum lum lum\" at any time.": "你現在開始了謙遜狩獵。在你放棄抗性保護期間的每一次擊殺，都將延續你的謙遜之路。你隨時可以說「Lum Lum Lum」來結束狩獵。",
    "you may not use this while it is in a container.": "當物品在容器中時你無法使用。",
    "you may not build any higher.": "你不能建造更高了。",
    "you do not have enough mana to keep your ability active.": "你沒有足夠的魔力維持你的能力。",
    "your ability was interrupted.": "你的能力被打斷了。",
    "your target is no longer in range of your ability.": "你的目標不再處於你的能力範圍內。",
    "your ability was canceled.": "你的能力已取消。",
    "you may not use a totem here.": "你不能在這裡使用圖騰。",
    "you cannot currently tame that creature.": "你目前無法馴服該生物。",
    "you lack the taming skill required to train this creature.": "你缺乏訓練此生物所需的馴獸技能。",
    "you may not use this item while it is in your backpack.": "當物品在你的背包中時你無法使用。",
    "you may not start a shadowguard encounter while in a party unless you are the party leader.": "你在隊伍中時無法開始暗影守衛（Shadowguard）遭遇戰，除非你是隊長。",
    "you must wait before trying to enter the fortress again. continued attempts will result in longer wait times.": "你必須等待才能再次嘗試進入要塞。持續嘗試將導致更長的等待時間。",
    "you have exceeded the max number of attempts at joining a shadowguard encounter. please try again later.": "你已超過加入暗影守衛遭遇戰的最大嘗試次數。請稍後再試。",
    "you cannot switch allegiance in the midst of the battle field!": "你不能在戰場中切換陣營！",
    "you cannot declare allegiance to that side.": "你不能宣布效忠該方。",
    "you have declared allegiance to the ~1_side~!  you may only change your allegiance once every 2 hours.": "你已宣布效忠 ~1_SIDE~！你每2小時只能改變一次陣營。",
    "you have already declared allegiance to the ~1_side~!  you may only change your allegiance once every 2 hours.": "你已宣布效忠 ~1_SIDE~！你每2小時只能改變一次陣營。",
    "you have won an auction for ~1_itemname~! your bid amount of ~2_bidamt~plat and ~3_bidamt~gp won the auction. you have 3 days from the end of the auction to claim your item or it will be lost.": "你贏得了 ~1_ITEMNAME~ 的拍賣！你的出價 ~2_BIDAMT~ 鉑金 ~3_BIDAMT~ 金幣贏得了拍賣。拍賣結束後你有3天時間領取物品，否則將遺失。",
    "you have been out bid in an auction for ~1_itemname~. the current winning bid amount is ~2_bidamt~plat and ~3_bidamt~gp.": "你在拍賣 ~1_ITEMNAME~ 中被超越出價。當前最高出價為 ~2_BIDAMT~ 鉑金 ~3_BIDAMT~ 金幣。",
    "your auction for ~1_itemname~ has ended with a winning bid of ~2_bidamt~plat and ~3_bidamt~gp. the winning bid has been deposited into your currency account.": "你的 ~1_ITEMNAME~ 拍賣已結束，得標價為 ~2_BIDAMT~ 鉑金 ~3_BIDAMT~ 金幣。得標金額已存入你的貨幣帳戶。",
    "you must wait for your auctioned item to be claimed before adding a new item.": "你必須等待拍賣物品被領取後才能添加新物品。",
    "you must wait for your auctioned item to be claimed before modifying this auction safe.": "你必須等待拍賣物品被領取後才能修改此拍賣保險箱。",
    "you cannot modify this while an auction is in progress.": "拍賣進行中你無法修改此項。",
    "your bid has been placed.": "你的出價已提交。",
    "you must set a starting bid.": "你必須設定起標價。",
    "you have been out bid.": "你已被超越出價。",
    "you must use an axe on this item to retrieve it.": "你必須用斧頭在此物品上才能取回。",
    "you can't use a bladed item on a wall safe with a balance.": "你不能對有餘額的壁掛保險箱使用鋒刃物品。",
    "you can't use a bladed item on an auction safe that has an auction item or is currently active.": "你不能對有拍賣物品或當前活躍的拍賣保險箱使用鋒刃物品。",
    "you cannot currently take this action because you have auction safes locked down in your home. you must remove them first.": "你目前無法執行此操作，因為你的房屋中有鎖定的拍賣保險箱。你必須先移除它們。",
    "you cannot commit this house design because housing customization is currently unavailable. please wait a few minutes and try again.": "你無法提交此房屋設計，因為房屋自訂目前不可用。請稍候幾分鐘再試。",
    "you do not have sufficient bronze ingots to make that.": "你沒有足夠的青銅錠來製作該物品。",
    "you cannot use this item while it is in your backpack.": "當物品在你的背包中時你無法使用。",
    "you may not open the barrel once fermentation has begun!": "發酵開始後你不能打開桶子！",
    "you empty the contents of the barrel.": "你清空了桶子的內容物。",
    "you may not rename the vintage once the fermentation process has begun.": "發酵過程開始後你不能重新命名年份。",
    "you may only put one type of fruit in the fermentation barrel at one time. empty the barrel first.": "你一次只能在發酵桶中放入一種水果。先清空桶子。",
    "you may not add anything to the fermentation barrel after fermentation has begun.": "發酵開始後你不能向發酵桶添加任何東西。",
    "the fermentation barrel is not empty. empty it first to add fruit and yeast.": "發酵桶不是空的。先清空才能添加水果和酵母。",
    "you may only put fruit and yeast in the fermentation barrel.": "你只能在發酵桶中放入水果和酵母。",
    "you may not eat that.": "你不能吃那個。",
    "you do not have enough fruit or yeast to begin fermentation.": "你沒有足夠的水果或酵母來開始發酵。",
    "you have already added yeast to the barrel.": "你已經在桶中添加了酵母。",
    "you may not wield a weapon and use this ability.": "你不能在裝備武器時使用此能力。",
    "you may not use this while it is in a container.": "當物品在容器中時你無法使用。",
    "you have received a mastery primer!": "你獲得了一本精通入門書！",
    "you cannot throw this there!": "你不能把這個扔到那裡！",
    "you may not use the stables while on a humility hunt.": "你在謙遜狩獵期間無法使用馬廄。",
    "you have added an auction safe to your broker.": "你已添加了一個拍賣保險箱到你的經紀人。",
    "you have removed an auction safe from your broker.": "你已從你的經紀人移除了一個拍賣保險箱。",
    "the broker is not able to add this auction safe at this time.": "經紀人目前無法添加此拍賣保險箱。",
    "the broker is not able to remove this auction safe at this time.": "經紀人目前無法移除此拍賣保險箱。",
    "you must be on the \"insecticide & regicide\" quest to enter.": "你必須正在進行「殺蟲與弒后」任務才能進入。",
    "you must be on the \"destruction of zipactriotl\" quest to enter.": "你必須正在進行「茲帕克特里奧特爾的毀滅」任務才能進入。",
    "you must pledge allegiance to the eodonians and defeat the myrmidex in the myrmidex pits before you can embark on this quest.": "你必須宣誓效忠伊歐頓人並在蟻族深坑擊敗蟻族才能開始此任務。",
    "you must pledge allegiance to the myrmidex and defeat the eodonians in the myrmidex pits before you can embark on this quest.": "你必須宣誓效忠蟻族並在蟻族深坑擊敗伊歐頓人才能開始此任務。",
    "you need at least ~1_skill_requirement~ ~2_skill_name~ skill to use that mastery.": "你需要至少 ~1_SKILL_REQUIREMENT~ 的 ~2_SKILL_NAME~ 技能才能使用該精通。",
    "you notice some of your fallen foe's equipment to be of kotl origin and decide it may be of some value...": "你注意到倒下的敵人裝備源自科特爾（Kotl），並判斷它可能有些價值……",
    "you have turned in ~1_count~ artifacts of the kotl": "你已繳交了 ~1_COUNT~ 件科特爾（Kotl）神器",
    "you take extra damage from the mortal wound!": "你因致命傷受到額外傷害！",
    "you cannot place this there!": "你不能將此放在那裡！",
    "you are too busy with your other quests, perhaps i will have something for you after you finish one of your current quests.": "你忙於其他任務，也許完成當前任務後我會有事找你。",
    "you cannot gain more spirituality.": "你無法獲得更多靈性。",
    "you have gained in spirituality.": "你的靈性提升了。",
    "you have gained a path in spirituality!": "你在靈性之路上取得了進展！",
    "you have lost some spirituality.": "你失去了一些靈性。",
    "they are already embraced by spirituality.": "他們已經被靈性擁抱。",
    "you can only embrace players and pets with spirituality.": "你只能對玩家和寵物施展靈性。",
    "your spirit has been embraced! you feel more powerful!": "你的靈魂被擁抱了！你感到更強大了！",
    "your spirit is no longer embraced. you feel less powerful.": "你的靈魂不再被擁抱。你感到力量減弱了。",
    "thy current transfer balance is ~1_amount~ platinum and ~2_amount~ gold.": "汝目前的轉移餘額為 ~1_AMOUNT~ 鉑金 ~2_AMOUNT~ 金幣。",
    "thy current secure balance is ~1_amount~ gold.": "汝目前的安全餘額為 ~1_AMOUNT~ 金幣。",
    "thy current bank balance is ~1_amount~ platinum and ~2_amount~ gold.": "汝目前的銀行餘額為 ~1_AMOUNT~ 鉑金 ~2_AMOUNT~ 金幣。",
    "~1_amount~ gold has been removed from your bank box.": "~1_AMOUNT~ 金幣已從你的銀行箱移除。",
    "~1_amount~ platinum has been deposited into your bank box.": "~1_AMOUNT~ 鉑金已存入你的銀行箱。",
    "thy current transfer balance is ~1_amount~ platinum and ~2_amount~ gold.": "汝目前的轉移餘額為 ~1_AMOUNT~ 鉑金 ~2_AMOUNT~ 金幣。",
    "thy generosity is most appreciated, however i cannot manage a donation of that magnitude.  perhaps you could reduce the amount of the donation.": "汝的慷慨令人感激，然而吾無法處理如此巨額的捐贈。或許汝可減少捐贈金額。",
    "your shard transfer balance is been reset.": "你的伺服器轉移餘額已重置。",
    "you have enabled pet training planning.": "你已啟用寵物訓練規劃。",
    "you have disabled pet training planning.": "你已停用寵物訓練規劃。",
    "you successfully train the pet!": "你成功訓練了寵物！",
    "you do not have the available pet slots to train this pet. please free up pet slots and try again.": "你沒有可用的寵物欄位來訓練此寵物。請釋放寵物欄位後再試。",
    "you are unable to train your pet. the required powerscroll was not found in your main backpack.": "你無法訓練寵物。主背包中未找到所需的力量卷軸。",
    "your pet lacks the required points to complete this training.": "你的寵物缺乏完成此訓練所需的點數。",
    "your pet looks to have already completed that training.": "你的寵物似乎已完成該訓練。",
    "your pet's control slot have been updated.": "你的寵物控制欄位已更新。",
    "you have not proven yourself...yet.": "你尚未證明自己……",
    "you must be a seeker of spirituality to invoke this virtue.": "你必須是靈性追尋者才能使用此美德。",
    "you have completed the first step on the path of the master!": "你完成了大師之路的第一步！",
    "you are currently already in the queue for one of the tower encounters.": "你當前已在其中一個塔樓遭遇戰的隊列中。",
    "you are currently already in the queue for the finale.": "你當前已在最終戰的隊列中。",
    "your winning bid amount of ~1_bidamt~plat and ~2_bidamt~gp for ~3_itemname~ has been refunded to you due to house collapse.": "你對 ~3_ITEMNAME~ 的得標金額 ~1_BIDAMT~ 鉑金 ~2_BIDAMT~ 金幣因房屋倒塌已退還給你。",
    "you have completed a quest!": "你已完成了一個任務！",
    "you will no longer receive city loyalty gain messages.": "你將不再收到城市忠誠度提升訊息。",
    "you will now receive city loyalty gain messages.": "你現在將收到城市忠誠度提升訊息。",
    "you need moonstone crystal shards to craft that.": "你需要月石水晶碎片來製作該物品。",
    "you need more of professor ellie rafkin's unabridged atlas of eodon.": "你需要更多艾莉·拉夫金（Ellie Rafkin）教授的伊歐頓完整地圖集。",
    "you have provided more than which has been requested by this deed.": "你提供的數量超過了此契約的要求。",
    "you gather some ~1_ingredient~": "你收集了一些 ~1_INGREDIENT~",
    "you must be the owner of that pet to have it repair.": "你必須是該寵物的主人才能讓它修理。",
    "you need 75 ~1_material~ ingots to repair the ~2_creature~.": "你需要 75 個 ~1_MATERIAL~ 錠來修理 ~2_CREATURE~。",
    "you must have at least 80 tinkering skill to attempt to repair ~1_creature~.": "你必須至少有 80 點工匠技能才能嘗試修理 ~1_CREATURE~。",
    "you loosen some rocks but fail to find any useable granite.": "你鬆動了一些岩石但未能找到可用的花崗岩。",
    "this tool is fully functional.": "此工具功能正常。",
    "this tool will only repair items in this mode.": "此工具在此模式下只會修理物品。",
    "target can not be repaired at this location.": "目標無法在此位置修理。",
    "the pet's owner must be nearby to attempt repair.": "寵物的主人必須在附近才能嘗試修理。",
    "a broken automaton head has been placed in your backpack.": "一個故障的自動機頭部已放入你的背包。",
    "you need 75 pieces of blackrock to repair the ~2_creature~.": "你需要 75 塊黑岩來修理 ~2_CREATURE~。",
    "the cider is not quite ready for serving yet.": "蘋果酒還沒準備好供應。",
    "the apples are not quite ready for serving yet.": "蘋果還沒準備好供應。",
    "the plant is not ready to be picked from.": "植物還沒準備好採摘。",
    "this item is impermissible and can not be added to the book.": "此物品不允許被加入書中。",
    "this book only holds power scrolls.": "此書只能存放力量卷軸。",
    "you have rescued ~1_count~ of ~2_max~ dragon turtle hatchlings.": "你已拯救了 ~1_count~ / ~2_max~ 隻龍龜幼崽。",
    "you have rescued ~1_count~ of ~2_max~ tiger cubs.": "你已拯救了 ~1_count~ / ~2_max~ 隻小老虎。",
    "you have recovered ~1_count~ of ~2_max~ lava rocks.": "你已收集了 ~1_count~ / ~2_max~ 塊熔岩。",
    "[quest event: getting even] you have won ~1_count~ of ~2_req~ games of ~3_game~!": "【任務事件：報仇雪恨】你已贏得 ~3_game~ 遊戲 ~1_count~ / ~2_req~ 局！",
    "you cut away some pelts, but they remain on the corpse.": "你切下了一些皮毛，但它們仍在屍體上。",
    "you cut away some scoots, but they remain on the corpse.": "你切下了一些皮，但它們仍在屍體上。",
    "you skin it, and place the pelts in your backpack.": "你剝下了皮毛，放入背包。",
    "you have bested this tower of shadowguard! you will be teleported out of the tower in 60 seconds!": "你已擊敗了這座暗影守衛（Shadowguard）塔樓！你將在60秒內被傳送出去！",
    "you have 5 minutes remaining in the encounter!": "你在遭遇戰中還有5分鐘！",
    "the encounter timer has expired!": "遭遇戰計時器已到期！",
    "you are currently already in the queue for the finale. you cannot join this queue unless you leave the other queue.": "你當前已在最終戰隊列中。除非離開其他隊列，否則無法加入此隊列。",
    "you are currently already in the queue for one of the tower encounters. you cannot join this queue unless you leave the other queue.": "你當前已在其中一個塔樓遭遇戰的隊列中。除非離開其他隊列，否則無法加入此隊列。",
    "all members of your party must complete each of the shadowguard towers before attempting the finale.": "你的隊伍所有成員必須先完成每個暗影守衛塔樓才能嘗試最終戰。",
    "congratulations! you have bested shadowguard and prevented minax from exploiting the time gate! you will be teleported out in a few minutes.": "恭喜！你已擊敗暗影守衛（Shadowguard），阻止了米娜克斯（Minax）利用時間之門！你將在幾分鐘內被傳送出去。",
    "there is a 30 minute time limit for each encounter. you will receive a time limit warning at 5 minutes.": "每次遭遇戰有30分鐘時限。你將在5分鐘時收到時限警告。",
    "you are not on the correct quest step to use this.": "你未處於正確的任務步驟來使用此物品。",
    "you not kill giant dino yet? sakkhra will not help until you kill big dino!": "你還沒殺死巨龍？薩克拉（Sakkhra）在你殺死巨龍之前不會幫助你！",
    "you not save dragon turtle hatchlings yet? urali will not help until you save dragon turtle hatchlings!": "你還沒拯救龍龜幼崽？烏拉利（Urali）在你拯救龍龜幼崽之前不會幫助你！",
    "you afraid of great volcano? ha ha! britannian afraid!": "你害怕大火山？哈哈！不列顛尼亞人害怕了！",
    "you save tiger cubs! they little and helpless! kurak will not help until you save tiger cubs!": "你救小老虎！牠們又小又無助！庫拉克（Kurak）在你救小老虎之前不會幫助你！",
    "you save tiger cubs! kurak thank you and help you!": "你救了小老虎！庫拉克（Kurak）感謝你並幫助你！",
    "you attack is ignored. you are not on the correct quest step.": "你的攻擊被忽略。你未處於正確的任務步驟。",
    "you may do this once every other month.": "你每隔一個月才能執行此操作。",
    "you have hired a gardener to tend to your plant.": "你已僱用了一名園丁照料你的植物。",
    "you prepare yourself to attempt to land three hits in rapid succession to the next target that damages you within a 2 tile radius.": "你準備好對2格範圍內的下一個傷害你的目標快速打出三連擊。",
    
    # === "Thy" messages ===
    "thy current transfer balance is ~1_amount~ platinum and ~2_amount~ gold.": "汝目前的轉移餘額為 ~1_AMOUNT~ 鉑金 ~2_AMOUNT~ 金幣。",
    "thy current secure balance is ~1_amount~ gold.": "汝目前的安全餘額為 ~1_AMOUNT~ 金幣。",
    "thy current bank balance is ~1_amount~ platinum and ~2_amount~ gold.": "汝目前的銀行餘額為 ~1_AMOUNT~ 鉑金 ~2_AMOUNT~ 金幣。",
    "thy generosity is most appreciated, however i cannot manage a donation of that magnitude.  perhaps you could reduce the amount of the donation.": "汝的慷慨令人感激，然而吾無法處理如此巨額的捐贈。或許汝可減少捐贈金額。",
    
    # === "This" messages ===
    "this item is already treated with tincture of silver!": "此物品已用銀質酊劑處理過！",
    "this property indicates that an item has increased durability loss and only can be powdered 3 times. each powder will reduce max durability to 250, 200, and 150 respectively. this item can be repaired.": "此屬性表示物品耐久度損失增加，且只能使用粉末強化3次。每次粉末將最大耐久度分別降低至250、200和150。此物品可被修理。",
    "this property indicates that an item has increased item insurance cost and cannot be blessed.": "此屬性表示物品保險費用增加且無法被祝福。",
    "this property indicates that an item cannot be shard transferred.": "此屬性表示物品無法進行伺服器轉移。",
    "this property indicates that an item can only be used by vice vs virtue players.": "此屬性表示物品僅能被邪惡vs美德玩家使用。",
    "this item can only be used on new magincia gardening plants.": "此物品僅能使用於新馬金西亞（New Magincia）園藝植物。",
    "this property has a chance to cause a swarm of insects to attack your opponent resulting in physical damage caused by insect bites.  this property can be found on select artifacts.": "此屬性有機會引發蟲群攻擊你的對手，造成昆蟲叮咬的物理傷害。此屬性可在特定神器中找到。",
    "this property provides a chance to cause energy damage over time that converts a percentage of the damage back to the attacker.  this property can be found on select artifacts.": "此屬性有機會造成持續能量傷害，並將部分傷害轉化回攻擊者。此屬性可在特定神器中找到。",
    "this property provides a chance to cause a loss of stamina over time and prevent the use of refreshment potions for a period of time to the target.  this property can be found on select artifacts.": "此屬性有機會造成目標持續失去體力，並在一段時間內無法使用恢復藥水。此屬性可在特定神器中找到。",
    "this property indicates that an item has increased item insurance cost and cannot be blessed.": "此屬性表示物品保險費用增加且無法被祝福。",
    "this tool can be used to add special brands to your pets to identify them unique to you!": "此工具可用於為你的寵物添加特殊烙印，以標識其為你獨有！",
    "this tool can only mine up granite.": "此工具只能開採花崗岩。",
    "this deed will be converted.": "此契約將被轉換。",
    "this item must be equipped or in your backpack to be used.": "此物品必須裝備或在背包中才能使用。",
    "this is an account-bound item which cannot be added.": "此為帳號綁定物品，無法添加。",
    "this ability requires additional skills the creature has not yet learned and will require additional training points.": "此能力需要生物尚未學會的額外技能，並需要額外的訓練點數。",
    "this selected pet cannot be branded by this branding iron.": "所選寵物無法被此烙印鐵烙印。",
    "this selected pet is not accessible to brand.": "所選寵物無法進行烙印。",
    "this creature's pet slot will be increased by one, after applying pet training options.": "此生物的寵物欄位將在應用寵物訓練選項後增加一格。",
    "this title is gained by battling against creatures of the valley of eodon.": "此稱號來自與伊歐頓（Eodon）山谷的生物戰鬥。",
    "this fermentation barrel can be used to create various wines by fermenting fruit.": "此發酵桶可用於通過發酵水果製作各種酒類。",
    "this creature's pet slot will be updated by starting the pet training process. do you wish to continue?": "此生物的寵物欄位將在開始訓練程序後更新。你確定要繼續嗎？",
    "this permit has already been submitted.": "此許可證已提交。",
    "this permit was documented in a different month or year than the current month and year. i only accept permits documented in the current month and year.": "此許可證記錄的月份或年份與當前不同。我只接受當月當年記錄的許可證。",
    "this auction is private.": "此拍賣為私人性質。",
    "this option has been disabled for 30 seconds due to a prior code entry or a store item search.": "由於先前的代碼輸入或商店物品搜索，此選項已禁用30秒。",
    "this is a reward title given for completing shadowguard.": "此為完成暗影守衛（Shadowguard）的獎勵稱號。",
    
    # === "The" messages ===
    "the professor": "教授",
    "the assembly has ended. you've earned some doubloons!": "集會已結束。你獲得了一些金幣！",
    "the barrel cannot hold anymore fruit.": "桶子無法容納更多水果了。",
    "the fermention process has already begun.": "發酵過程已經開始。",
    "the fermentation process has begun.": "發酵過程已開始。",
    "the fermentation process has not been started.": "發酵過程尚未開始。",
    "the plant is not ready to be picked from.": "植物還沒準備好採摘。",
    "the pet was not branded.": "寵物未被烙印。",
    "the branding failed.": "烙印失敗。",
    "the item is not made from the requested resource.": "該物品並非由要求的資源製成。",
    "both orders must use the same resource type.": "兩個訂單必須使用相同的資源類型。",
    "the activators have already been solved.": "啟動器已被解決。",
    "the wheels of time have already been set in motion.": "時間之輪已被啟動。",
    "the amount entered is invalid. verify that there are sufficient funds to complete this transaction.": "輸入的金額無效。請確認有足夠資金完成此交易。",
    "the life of an animal trainer is not for everyone, return to an animal trainer if you wish to try again.": "動物訓練師的生活不適合所有人，如果你想再試一次，請回到動物訓練師處。",
    "the time lord. that is how he will be known": "時間之主。這就是他將為人所知的名字。",
    "the fortres is currently full right now. you are currently ~1_num~ in the queue.": "要塞目前已滿。你目前在隊列中的位置是 ~1_NUM~。",
    
    # === "A" messages ===
    "a charge could not be refunded to the last forged metal of artifacts tool you used, you must use this charge.": "無法將使用次數退還到上一個使用的神器鍛造金屬工具，你必須使用此使用次數。",
    "a charge could not be refunded to the last forged metal of artifacts tool you used because the item is not in your backpack.": "無法將使用次數退還到上一個使用的神器鍛造金屬工具，因為物品不在你的背包中。",
    "a charged has been refunded to your forged metal of artifacts tool.": "使用次數已退還到你的神器鍛造金屬工具。",
    "a gardener is already tending to this plant.": "已有園丁在照料此植物。",
    "a reward of ~1_item~ has been placed in your bank.": "獎勵 ~1_ITEM~ 已放入你的銀行。",
    "a special map thought to lead to lost kotl technology": "被認為指向失落科特爾（Kotl）科技的特別地圖",
    "a bag with a unique treasure": "裝有獨特寶藏的袋子",
    "a step closer to quelling the myrmidex threat...": "向平息蟻族（Myrmidex）威脅邁進了一步……",
    "a step closer to destroying zipactriotl...": "向毀滅茲帕克特里奧特爾（Zipactriotl）邁進了一步……",
    "a step closer to destroying the myrmidex queen...": "向毀滅蟻后邁進了一步……",
    "a step closer to mastering animal training.": "向掌握動物訓練邁進了一步。",
    "a totem is already active in this area.": "該區域已有一個圖騰生效。",
    "a drain": "排水口",
    "a spigot": "水龍頭",
    "a special gift for ~1_name~": "給 ~1_NAME~ 的特別禮物",
    "a portion of this item would not be inside the home.  try again.": "此物品的一部分將不在房屋內。請重試。",
    "a specially lined keg for powder of fortification.": "一個專門用於強化粉末的內襯小桶。",
    
    # === "Are you sure" ===
    "are you sure you wish to apply the selected skill bonus to this item?": "你確定要將所選技能加成應用於此物品嗎？",
    "are you sure you wish to exit shadowguard?": "你確定要退出暗影守衛（Shadowguard）嗎？",
    "are you sure you want to complete this purchase?": "你確定要完成此購買嗎？",
    "are you sure you wish to end the fermentation process? all progress and materials will be lost!": "你確定要結束發酵過程嗎？所有進度和材料都將遺失！",
    "are you sure you wish to start the fermentation process?": "你確定要開始發酵過程嗎？",
    
    # === "That" messages ===
    "that is not a valid kill.": "那不是有效的獵殺。",
    "that is not something that can be ground.": "那不是可以研磨的東西。",
    "that pet has already embraced humility.": "該寵物已被施展謙遜。",
    "that item is not an auction safe.": "該物品不是拍賣保險箱。",
    "that's not your gift!": "那不是你的禮物！",
    
    # === "Please" messages ===
    "please choose a skill": "請選擇一項技能",
    "please see banker to deposit currency that was transferred.": "請找銀行員存入已轉移的貨幣。",
    "please wait for your purchase to complete.": "請等待購買完成。",
    "please make a selection:": "請做出選擇：",
    
    # === "Enter" prompts ===
    "enter the characters you wish to push...": "輸入你想要按下的字符……",
    "enter amount of gold to add to shard transfer balance from current account balance of ~1_amount~:": "從當前 ~1_AMOUNT~ 的帳戶餘額中輸入要添加到伺服器轉移餘額的金幣數量：",
    "enter amount of platinum to add to shard transfer balance from current account balance of ~1_amount~:": "從當前 ~1_AMOUNT~ 的帳戶餘額中輸入要添加到伺服器轉移餘額的鉑金數量：",
    "enter the amount of gold you wish to deposit (esc = cancel):": "輸入你想要存入的金幣數量（ESC = 取消）：",
    
    # === "Target" prompts ===
    "target the kill you wish to document": "選擇你想要記錄的獵殺目標",
    "target the weapon, spellbook, or instrument you wish to apply this to...": "選擇你想要應用的武器、法術書或樂器……",
    "target the new magincia plant you wish to have a gardener tend to...": "選擇你想要園丁照料的新馬金西亞（New Magincia）植物……",
    "target the pet you wish to embrace with your humility...": "選擇你想要施展謙遜的寵物……",
    "target whom you wish to embrace with your spirituality...": "選擇你想要施展靈性的目標……",
    "select a pet to brand.": "選擇要烙印的寵物。",
    "target your pet to begin training.": "選擇你的寵物開始訓練。",
    
    # === Confirmation ===
    "all pet training is final and can't be unlearned. do you want to complete this training?": "所有寵物訓練均為最終決定且無法撤銷。你確定要完成此訓練嗎？",
    "pet training confirmation": "寵物訓練確認",
    "initiating training for this pet will remove pack instincts. pack instincts is restricted on pets four slots and above. do you wish to continue?": "開始訓練此寵物將移除族群本能。族群本能僅限於4欄位及以上的寵物。你確定要繼續嗎？",
    "pet slot adjustment warning": "寵物欄位調整警告",
    "this creature's pet slot will increase by one, after applying pet training options. do you wish to continue?": "應用寵物訓練選項後，此生物的寵物欄位將增加一格。你確定要繼續嗎？",
    "select training": "選擇訓練",
    
    # === Dialogue / questions ===
    "what artifacts?": "什麼神器？",
    "what have you excavated?": "你們挖掘到了什麼？",
    "what is the crest?": "那是什麼紋章？",
    "what is this place?": "這是什麼地方？",
    "who told you i was coming?": "誰告訴你我會來？",
    "how...how could this happen! i shall nay be bested by mere mortals! we shall meet again vile heroes!": "怎……怎麼可能！我不可能被區區凡人擊敗！我們會再次相遇的，卑鄙的英雄們！",
    "well done! i don't know how you managed to pull it off but this is the break we've been waiting for!": "做得好！我不知道你是怎麼做到的，但這就是我們一直等待的突破！",
    "well done! with these pests out of my gardens i can finally get on with growing a prized lettuce!": "做得好！這些害蟲離開我的花園後，我終於可以繼續種植珍貴的萵苣了！",
    "well color me surprised, you did it!": "真是讓我吃驚，你做到了！",
    "well if you're afraid of a little bunny then you haven't much business tackling a myrmidex. hrmph!": "哼，如果你連一隻小兔子都怕，那就沒什麼資格對付蟻族（Myrmidex）。哼！",
    "no time to waste on those uncommitted to the cause - be gone with you!": "沒時間浪費在對事業不忠誠的人身上——走吧！",
    "so precious, the most precious of stones desired by our myrmidex overlords...": "如此珍貴，我們蟻族（Myrmidex）霸主所渴望的最珍貴寶石……",
    "all hail our myrmidex overlords!": "向我們的蟻族（Myrmidex）霸主致敬！",
    "muwahaha! zipactriotl is destroyed! the myrmidex are free to reclaim eodon!": "穆哇哈哈！茲帕克特里奧特爾（Zipactriotl）被毀滅了！蟻族（Myrmidex）自由了，可以收復伊歐頓（Eodon）！",
    "i should be excited but i cannot help but grimace at the destruction of an entire population": "我本該興奮，但對整個族群的毀滅仍不禁感到苦澀。",
    "i must question your commitment to our cause - are you satisfied with these myrmidex invaders and their barrabian allies?": "我必須質疑你對我們事業的承諾——你對這些蟻族（Myrmidex）入侵者及其巴拉布（Barrab）盟友感到滿意嗎？",
    "i must question your commitment to the myrmidex - are you satisfied with these britannian invaders and their eodonian allies?": "我必須質疑你對蟻族（Myrmidex）的承諾——你對這些不列顛尼亞入侵者及其伊歐頓盟友感到滿意嗎？",
    "i can only work with artifacts that are in pristine condition.": "我只能處理處於完好狀態的神器。",
    "i am the exalted artificer. hand me select human artifacts to convert them for gargoyle use.": "我是崇高的工匠大師。把特定人類神器交給我，將它們轉化為石像鬼可用。",
    "i knew it, you must be yellar! get out of my sight!": "我就知道，你一定是膽小鬼！滾出我的視線！",
    "i'm sorry, i cannot accept this item.": "抱歉，我無法接受此物品。",
    "so you're saying i can't have them...": "所以你是說我不能擁有它們……",
    "no you cannot have them! i cannot condone the theft of antiques that have been claimed by the research team here!": "不，你不能擁有它們！我不能容忍盜竊已被研究團隊申報的古董！",
    "you knew i was coming?": "你知道我要來？",
    "you can see the future?!": "你能看見未來？！",
    "mondain the wizard?!": "巫師蒙丹？！",
    "vice and virtue?": "邪惡與美德？",
    "murdered his father!?": "弒父！？",
    "teleport to nearest moongate?": "傳送到最近的月門？",
    "who told you i was coming?": "誰告訴你我會來？",
    "what is this place?": "這是什麼地方？",
    "nothing happens.": "什麼也沒發生。",
    "plaque": "牌匾",
    
    # === Various other entries ===
    "sanctuary, blackthorn.": "sanctuary, blackthorn.",
    "bring me items of doom and i will reward you with valuable items.": "帶末日（Doom）物品給我，我將以貴重物品回報你。",
    "turn in artifacts of the kotl": "繳交科特爾（Kotl）神器",
    "claim rewards": "領取獎勵",
    "artifacts of doom trader": "末日（Doom）神器商人",
    "artifacts of doom": "末日（Doom）神器",
    "what can i interest you in...": "有什麼能引起你的興趣……",
    "when applied:": "使用效果：",
    "200% damage increase towards ~1_name~": "對 ~1_NAME~ 造成 200% 傷害加成",
    "undead vulnerability": "不死生物弱點",
    "not antique": "非古董",
    "select a reward title deed:": "選擇獎勵稱號契約：",
    "reward title scroll": "獎勵稱號卷軸",
    "a skill bonus has been applied to the item!": "技能加成已應用於物品！",
    "double click to set skill bonus": "雙擊以設定技能加成",
    "double click to join huntmaster's challenge": "雙擊加入狩獵大師挑戰賽",
    "double click to declare or check allegiance": "雙擊以宣告或檢查陣營",
    "teleport to nearest moongate?": "傳送到最近的月門？",
    "get hunting permit": "領取狩獵許可證",
    "hunter: ~1_name~": "獵人：~1_NAME~",
    "date of kill: ~1_date~": "獵殺日期：~1_DATE~",
    "wingspan: ~1_val~ feet": "翼展：~1_VAL~ 英尺",
    "length: ~1_val~ feet": "體長：~1_VAL~ 英尺",
    "species: ~1_type~": "種類：~1_TYPE~",
    "beverages": "飲料",
    "adding this to the power tool would put it over the max number of charges the tool can hold.": "將此加入動力工具會超過工具可容納的最大使用次數。",
    "charges have been added to the power tool.": "使用次數已加入動力工具。",
    "nomination period ends after: ~1_date~": "提名期結束於：~1_DATE~",
    "voting period ends after: ~1_date~": "投票期結束於：~1_DATE~",
    "city stone": "城市之石",
    "gardening contract expires: ~1_time~": "園藝合約到期：~1_TIME~",
    "gardening contract": "園藝合約",
    "valentine's day picnic basket": "情人節野餐籃",
    "a freshly picked rose": "剛摘的玫瑰",
    "stone walls": "石牆",
    "what do you wish to grind?": "你想研磨什麼？",
    "what do you wish to call this vintage?": "你想給這批年份酒取什麼名字？",
    "toggle: on/off": "切換：開/關",
    "auto ignore corpses": "自動忽略屍體",
    "character backpack style": "角色背包樣式",
    "stall leases": "攤位租約",
    "stall lease": "攤位租約",
    "pet training options": "寵物訓練選項",
    "requirements": "需求",
    "increase a creature's strength.": "提升生物的力量。",
    "increase a creature's dexterity.": "提升生物的敏捷。",
    "increase a creature's intelligence.": "提升生物的智力。",
    "increase a creature's maximum hit points.": "提升生物的最大生命值。",
    "increase a creature's maximum stamina.": "提升生物的最大體力。",
    "increase a creature's maximum mana.": "提升生物的最大魔力。",
    "increase a creature's natural hit point regeneration rate.": "提升生物的自然生命回復速度。",
    "increase a creature's natural stamina regeneration rate.": "提升生物的自然體力回復速度。",
    "increase a creature's natural mana regeneration rate.": "提升生物的自然魔力回復速度。",
    "increase a creature's base damage per second average.": "提升生物的基礎每秒平均傷害。",
    "increase a creature's physical resistance.": "提升生物的物理抗性。",
    "increase a creature's fire resistance.": "提升生物的火焰抗性。",
    "increase a creature's cold resistance.": "提升生物的冰冷抗性。",
    "increase a creature's energy resistance.": "提升生物的能量抗性。",
    "increase a creature's poison resistance.": "提升生物的毒素抗性。",
    "increase a creature's specific skill cap with the use of powerscrolls.": "使用力量卷軸提升生物的特定技能上限。",
    "health": "生命",
    "stamina": "體力",
    "mana": "魔力",
    "strength": "力量",
    "dexterity": "敏捷",
    "intelligence": "智力",
    "physical resist": "物理抗性",
    "fire resist": "火焰抗性",
    "cold resist": "冰冷抗性",
    "energy resist": "能量抗性",
    "poison resist": "毒素抗性",
    "physical": "物理",
    "fire": "火焰",
    "cold": "冰冷",
    "energy": "能量",
    "poison": "毒素",
    "hit point increase": "生命值增加",
    "hit point regeneration": "生命回復",
    "stamina regeneration": "體力回復",
    "mana regeneration": "魔力回復",
    "swing speed increase": "攻擊速度增加",
    "hit chance increase": "命中機率增加",
    "defense chance increase": "防禦機率增加",
    "damage increase": "傷害增加",
    "lower mana cost": "降低魔力消耗",
    "faster casting": "快速施法",
    "spell damage increase": "法術傷害增加",
    "lower requirements": "降低需求",
    "self repair": "自我修復",
    "mage armor": "法師護甲",
    "use best weapon skill": "使用最佳武器技能",
    "spell channeling": "法術引導",
    
    # === Short entries ===
    "recycle": "回收",
    "unused": "未使用",
    "select one:": "選擇一項：",
    "choose your path:": "選擇你的道路：",
    
    # === Fermentation ===
    "begin fermentation": "開始發酵",
    "empty barrel": "清空桶子",
    "rename vintage": "重新命名年份",
    "how...how could this happen! i shall nay be bested by mere mortals! we shall meet again vile heroes!": "怎……怎麼可能！我不可能被區區凡人擊敗！我們會再次相遇的，卑鄙的英雄們！",
    "you shall burn as trinsic burned at the hands of the vile lich juo'nar!": "你將如特林西克（Trinsic）在邪惡巫妖朱奧納爾（Juo'nar）手中燃燒一般被焚燒！",
    "oh anon my dear! deal with these pesky intruders will you? burn them to ash!": "噢，親愛的安儂（Anon）！處理掉這些討厭的入侵者好嗎？把他們燒成灰燼！",
    "you didn't think that ridiculous pie trick would work twice in a row? virtuebane i command thee destroy these vile creatures!": "你以為那個可笑的餡餅把戲能連續成功兩次？維秋貝恩（Virtuebane），我命令你消滅這些邪惡的生物！",
    "and now you shall bow to the king of kings! suffer at the hands of the feudal lord ozymandias!": "現在你將向萬王之王屈膝！在封建領主奧茲曼迪亞斯（Ozymandias）手下受苦吧！",
    
    # === Short action text ===
    "*the vase shatters as you cut away the sealing wax!\"": "*在你切開封蠟時，花瓶碎裂了！",
    
    # === Anniversary messages ===
    "happy 18th anniversary! we have placed a gift for you in your backpack.": "18週年快樂！我們已將禮物放入你的背包。",
    "happy 18th anniversary! we have placed a gift for you in your bank box.": "18週年快樂！我們已將禮物放入你的銀行箱。",
    "happy 18th anniversary! to get your gift, please remove some items from your backpack or bank and log back in.": "18週年快樂！要領取禮物，請從背包或銀行取出一些物品後重新登入。",
    "happy 19th anniversary! we have placed a gift for you in your backpack.": "19週年快樂！我們已將禮物放入你的背包。",
    "happy 19th anniversary! we have placed a gift for you in your bank box.": "19週年快樂！我們已將禮物放入你的銀行箱。",
    "happy 19th anniversary! to get your gift, please remove some items from your backpack or bank and log back in.": "19週年快樂！要領取禮物，請從背包或銀行取出一些物品後重新登入。",
    "happy anniversary! please choose a gift:": "週年快樂！請選擇一份禮物：",
    "in commemoration of nineteen amazing years! thank you and happy anniversary!": "紀念精彩的十九年！感謝您，週年快樂！",
    
    # === Forged Metal ===
    "forged metal of artifacts provides a 100% success rate on an item enhancement (10 charges).": "神器鍛造金屬提供100%的物品強化成功率（10次使用次數）。",
    "forged metal of artifacts provides a 100% success rate on an item enhancement (5 charges).": "神器鍛造金屬提供100%的物品強化成功率（5次使用次數）。",
    
    # === Master Craftman entries ===
    "master craftsman talisman<br>improves crafting success<br>provides crafting failure protection<br>charges: 25": "工匠大師護符<br>提高製作成功率<br>提供製作失敗保護<br>使用次數：25",
    "master craftsman talisman<br>improves crafting success<br>provides crafting failure protection<br>charges: 10": "工匠大師護符<br>提高製作成功率<br>提供製作失敗保護<br>使用次數：10",
    "master craftsman talisman<br>improves crafting success<br>provides crafting failure protection<br>charges: 50": "工匠大師護符<br>提高製作成功率<br>提供製作失敗保護<br>使用次數：50",
    "master craftsman apron<br>improves crafting results<br>this apron comes in hues not normally available.": "工匠大師圍裙<br>提高製作結果<br>此圍裙為非通常可用色調。",
    
    # === Purchase / Store messages ===
    "your purchase of ~1_item~ will be delivered to you once you free up room in your backpack.": "你的 ~1_ITEM~ 購買將在背包騰出空間後送達。",
    "your purchase of ~1_item~ will be delivered to you once you are resurrected.": "你的 ~1_ITEM~ 購買將在你復活後送達。",
    "your purchased item will be delivered to you once you are resurrected.": "你購買的物品將在你復活後送達。",
    "your purchased will be delivered to you once you free up room in your backpack.": "你的購買將在背包騰出空間後送達。",
    "purchase failed due to one of your items no longer being available.": "購買失敗，因為你的其中一件物品不再可用。",
    "purchase failed due to your cart being empty.": "購買失敗，因為你的購物車是空的。",
    "your cart is currently locked while your transaction completes.": "交易進行期間你的購物車已鎖定。",
    "your cart is currently full.": "你的購物車已滿。",
    "failed to process one of your items. please check your cart and try again.": "處理你的其中一件物品失敗。請檢查購物車後重試。",
    "your purchased item has been placed in your backpack.": "你購買的物品已放入你的背包。",
    "your purchase of ~1_item~ has been placed in your backpack.": "你購買的 ~1_ITEM~ 已放入你的背包。",
    "you can't exceed 125 items per purchase.": "每次購買不能超過125件物品。",
    "your store cart is currently full.": "你的商店購物車已滿。",
    "this transaction cannot be completed due to insufficient funds available. visit the origin store to purchase sovereigns.": "由於資金不足，此交易無法完成。請訪問起源商店購買主權幣。",
    "insufficient funds": "資金不足",
    "add funds": "添加資金",
    "purchase confirmation": "購買確認",
    "before using the in game store, you must be in a safe log-out location (such as an inn or a house which has you on its owner, co-owner, or friends list).": "在使用遊戲內商店之前，你必須位於安全登出位置（如旅館或你位於所有者、共同所有者或好友列表中的房屋）。",
    
    # === Misc system messages ===
    "there was an error with your transaction. verify that your balance for this action is below 2,000,000,000.": "交易出現錯誤。請確認你此操作的餘額低於2,000,000,000。",
    "there was an error with your transaction. verify that your balance for this action is not greater than 100,000,000.": "交易出現錯誤。請確認你此操作的餘額不大於100,000,000。",
    "there was an error with your transaction. your secure balance can't be greater than 100,000,000.": "交易出現錯誤。你的安全餘額不能大於100,000,000。",
    "there are no charges left on this branding iron.": "此烙印鐵已無使用次數。",
    "there is no active auction to complete this action.": "沒有進行中的拍賣來完成此操作。",
    "there is little time to delay. deliver the orders to sir geoffrey at his camp near the barrab tribe in the valley of eodon.": "刻不容緩。將命令送到伊歐頓（Eodon）山谷巴拉布（Barrab）部落附近營地中的傑弗里（Geoffrey）爵士那裡。",
    "there are new items in the ultima store.": "不列顛尼亞商店（Ultima Store）有新物品上架。",
    "your talisman magically saves your crafting resources.": "你的護符神奇地保存了你的製作資源。",
    "your talisman magically improves your spellbook.": "你的護符神奇地強化了你的法術書。",
    "your talisman has been destroyed.": "你的護符已被摧毀。",
    "some of the items could not be created because there is not enough empty space in the container.": "部分物品無法創建，因為容器中沒有足夠的空白空間。",
    "have you seen the latest items available in the ultima store?": "你看過不列顛尼亞商店（Ultima Store）的最新物品了嗎？",
    "have you checked out what's new in the ultima store?": "你查看過不列顛尼亞商店（Ultima Store）的新品了嗎？",
    "visit store": "前往商店",
}

# Apply translations
translated_count = 0
for key, eng_text in untranslated:
    eng_lower = eng_text.strip().lower()
    
    if eng_lower in translations:
        output[key] = translations[eng_lower]
        translated_count += 1
    elif eng_text in translations:
        output[key] = translations[eng_text]
        translated_count += 1

# Write output
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=1)

# Verify
chinese_count = 0
english_count = 0
for v in output.values():
    if v and has_chinese(v):
        chinese_count += 1
    elif v:
        english_count += 1

print(f"Newly translated: {translated_count}")
print(f"Total entries with Chinese: {chinese_count}/{len(output)}")
print(f"Total entries still English: {english_count}/{len(output)}")

# Show remaining English entries
if english_count > 0:
    print("\n=== Remaining English entries ===")
    for k, v in source.items():
        ov = output.get(k, '')
        if ov and not has_chinese(ov):
            print(f"  {k}: {v[:120]}")
            english_count -= 1
            if english_count <= 0:
                break
