#!/usr/bin/env python3
"""Translate batch 10-game-text-4.json English to Traditional Chinese."""

import json
import os
import re

# Paths
source_path = '/Users/forrrest/projects/UO-Memento/ultima-memento/World/Data/Localization/tools-output/cliloc-batches/groups/10-game-text-4.json'
output_dir = '/Users/forrrest/projects/UO-Memento/ultima-memento/World/Data/Localization/tools-output/cliloc-batches/responses'
output_path = os.path.join(output_dir, 'response-10-game-text-4.json')

with open(source_path, 'r') as f:
    source = json.load(f)

def translate_en_to_zh(t):
    """Translate English game text to Traditional Chinese, preserving placeholders/HTML."""
    t_original = t
    t = t.strip()
    if not t:
        return ""
    
    # === EXACT MATCH MAP ===
    exact = {
        "sanctuary, blackthorn.": "sanctuary, blackthorn.",
        "~1_ITEM~ of Doom": "~1_ITEM~ 的末日",
        "~1_NAME~'s Lantern of Light": "~1_NAME~ 的光明提燈",
        "[Your Character Name]'s Lantern of Light": "[你的角色名稱] 的光明提燈",
        "Sterling Silver Ring": "純銀戒指",
        "Boots of Escaping": "逃脫之靴",
        "Cloak of Light": "光明斗篷",
        "Tincture of Silver": "銀質酊劑",
        "Silvered": "鍍銀",
        "Sceptre of Pride": "傲慢權杖",
        "Crook of Humility": "謙遜曲杖",
        "Ancient Clay Vase": "古陶瓶",
        "Ancient Parchment": "古代卷軸",
        "Antique Documents Kit": "古董文件套組",
        "Prophetic Manuscript": "預言手稿",
        "The Blind Prophet": "盲眼先知",
        "Talons of Escaping": "逃脫之爪",
        "Wing Armor of Light": "光明翼甲",
        "Power Scroll Book": "力量卷軸書",
        "Wondrous (105)": "非凡（105）",
        "Exalted   (110)": "崇高（110）",
        "Mythical  (115)": "神話（115）",
        "Legendary (120)": "傳奇（120）",
        "Power Scrolls": "力量卷軸",
        "Blue Marble Fireplace": "藍色大理石壁爐",
        "Gold Marble Fireplace": "金色大理石壁爐",
        "Green Marble Fireplace": "綠色大理石壁爐",
        "Happy Holidays 2014": "2014 節日快樂",
        "Coffee Grounds": "咖啡粉",
        "Hunting Permit": "狩獵許可證",
        "Turkey": "火雞",
        "Boar": "野豬",
        "Walrus": "海象",
        "Alligator": "短吻鱷",
        "Ancient Hell Hound Statuette": "古代地獄犬雕像",
        "Ridable Ancient Hell Hound Statuette": "可騎乘古代地獄犬雕像",
        "Huntmaster's Challenge": "狩獵大師挑戰賽",
        "Huntmaster's Champion": "狩獵大師冠軍",
        "Brew": "釀造",
        "Coffee": "咖啡",
        "Hot Cocoa": "熱可可",
        "Platinum Dragon Statuette": "鉑金龍雕像",
        "Flesh Renderer Statuette": "血肉撕裂者雕像",
        "Crystal Elemental Statuette": "水晶元素雕像",
        "Dark Father Statuette": "黑暗之父雕像",
        "Magery Mastery": "魔法精通",
        "Mysticism Mastery": "神秘主義精通",
        "Necromancy Mastery": "死靈法術精通",
        "Spellweaving Mastery": "法術編織精通",
        "Bushido Mastery": "武士道精通",
        "Chivalry Mastery": "騎士精神精通",
        "Ninjitsu Mastery": "忍術精通",
        "Fencing Mastery": "刺擊術精通",
        "Mace Fighting Mastery": "錘術精通",
        "Swordsmanship Mastery": "劍術精通",
        "Throwing Mastery": "投擲術精通",
        "Parrying Mastery": "格擋精通",
        "Poisoning Mastery": "用毒精通",
        "Wrestling Mastery": "搏擊精通",
        "Animal Taming Mastery": "馴獸精通",
        "Archery Mastery": "弓術精通",
        "Stone Walls": "石牆",
        "Rough Windowless": "粗糙無窗",
        "Rough Window": "粗糙窗戶",
        "Rough Arch": "粗糙拱門",
        "Rough Pillar": "粗糙柱子",
        "Rough Rounded Arch": "粗糙圓拱",
        "Path of Humility": "謙遜之路",
        "Rough Small Arch": "粗糙小拱門",
        "Rough Angled Pillar": "粗糙斜柱",
        "Short Rough": "短粗糙",
        "Stone Stairs": "石階梯",
        "Rough Block": "粗糙方塊",
        "Rough Steps": "粗糙台階",
        "Spirituality Virtue Shield": "靈性美德護盾",
        "Rough Corner Steps": "粗糙角落階梯",
        "Rough Rounded Corner Steps": "粗糙圓角階梯",
        "Rough Inset Steps": "粗糙嵌入式階梯",
        "Rough Rounded Inset Steps": "粗糙圓角嵌入式階梯",
        "Small Display Case (South)": "小型展示櫃（南）",
        "Small Display Case (East)": "小型展示櫃（東）",
        "Large Display Case (South)": "大型展示櫃（南）",
        "Large Display Case (East)": "大型展示櫃（東）",
        "Dark Wooden Sign Hanger": "深色木製招牌架",
        "Light Wooden Sign Hanger": "淺色木製招牌架",
        "Curled Metal Sign Hanger": "捲曲金屬招牌架",
        "Flourished Metal Sign Hanger": "花式金屬招牌架",
        "Inward Curled Metal Sign Hanger": "內捲金屬招牌架",
        "End Curled Metal Sign Hanger": "末端捲曲金屬招牌架",
        "Currency Wall Safe": "貨幣壁掛保險箱",
        "Stone Floor": "石地板",
        "Light Paver": "淺色鋪路石",
        "Medium Paver": "中色鋪路石",
        "Dark Paver": "深色鋪路石",
        "Primer on ~1_Skill~": "~1_Skill~ 入門",
        "Volume ~1_Level~": "第 ~1_Level~ 卷",
        "Rampage": "狂暴",
        "Death Ray": "死亡射線",
        "Ethereal Burst": "虛空爆發",
        "Nether Blast": "虛空爆破",
        "Mystic Weapon": "神秘武器",
        "Command Undead": "命令不死",
        "Conduit": "傳導管",
        "Mana Shield": "魔力護盾",
        "Summon Reaper": "召喚收割者",
        "Enchanted<br>Summoning": "附魔<br>召喚",
        "Anticipate Hit": "預判攻擊",
        "Warcry": "戰吼",
        "Intuition": "直覺",
        "Rejuvenate": "恢復活力",
        "Holy Fist": "神聖之拳",
        "Shadow": "暗影",
        "White Tiger Form": "白虎形態",
        "Flaming Shot": "火焰射擊",
        "Playing the Odds": "賭注",
        "Thrust": "突刺",
        "Pierce": "穿透",
        "Stagger": "擊退",
        "Toughness": "堅韌",
        "Onslaught": "猛攻",
        "Focused Eye": "專注之眼",
        "Elemental Fury": "元素之怒",
        "Calledshot": "精準射擊",
        "Saving Throw": "豁免投擲",
        "Shield Bash": "盾擊",
        "Bodyguard": "保鏢",
        "Heighten Senses": "強化感官",
        "Tolerance": "耐受",
        "Injected Strike": "注射打擊",
        "Potency": "效力",
        "Fists of Fury": "憤怒之拳",
        "Knockout": "擊倒",
        "Whispering": "低語",
        "Combat Training": "戰鬥訓練",
        "Boarding": "登船",
        "Placeholder": "佔位符",
        "Korean": "韓文",
        "Jungle Walls": "叢林牆壁",
        "Shadowguard Walls": "暗影守衛之牆",
        "Jungle Arches": "叢林拱門",
        "Shadowguard Arches": "暗影守衛拱門",
        "Jungle": "叢林",
        "Shadowguard": "暗影守衛",
        "Jungle Doors": "叢林門",
        "Shadowguard Doors": "暗影守衛之門",
        "Jungle Roof": "叢林屋頂",
        "Shadowguard Roof": "暗影守衛屋頂",
        "Balakai's Shaman Staff": "巴拉凱的薩滿法杖",
        "Eodon Slayer": "伊歐頓殺手",
        "Halawa's Hunting Bow": "哈拉瓦的狩獵弓",
        "Lerei's Hunting Spear": "萊雷的狩獵矛",
        "Grugor's Shield": "格魯戈爾的盾牌",
        "Jumu's Sacred Hide": "朱穆的聖皮",
        "Moctapotl's Obsidian Sword": "莫克塔波特的黑曜石劍",
        "Wamap's Bone Earrings": "瓦馬普的骨耳環",
        "Myrmidex Drone": "蟻族雄蜂",
        "Myrmidex Warrior": "蟻族戰士",
        "Msafiri Armor": "姆薩菲里護甲",
        "18th Anniversary Gift Bag": "18週年禮物袋",
        "Tall 18th Anniversary Vase": "高型18週年花瓶",
        "Short 18th Anniversary Vase": "矮型18週年花瓶",
        "An Ornately Decorated Commemorative Plate": "華麗裝飾紀念盤",
        "Purifying Flames": "淨化之焰",
        "Corrupt Phylactery": "腐化護命匣",
        "Purified Phylactery": "淨化護命匣",
        "Shattered Metal": "碎裂金屬",
        "Mastery Index": "精通索引",
        "Active Mastery": "當前精通",
        "Canal": "渠道",
        "Flowing Trough": "流水槽",
        "Bell Stand": "鐘架",
        "Feeding Bell": "餵食鐘",
        "Magic Drake Wing": "魔法龍翼",
        "An Enchanting Crystal Ball": "迷人的水晶球",
        "Donate Gold": "捐贈金幣",
        "Dragon Turtle": "龍龜",
        "Darden's Armor": "達登的護甲",
        "Aloron's Armor": "阿洛隆的護甲",
        "Valley of Eodon": "伊歐頓山谷",
        "Tiger Pelts": "虎皮",
        "A Drain": "排水口",
        "A Spigot": "水龍頭",
        "Myrmidex Larvae": "蟻族幼蟲",
        "silverback gorilla": "銀背大猩猩",
        "Infernus": "煉獄",
        "Dimetrosaur": "雙脊龍",
        "Allosaurus": "異特龍",
        "Gallusaurus": "雞龍",
        "Archaeosarus": "始祖龍",
        "Najasaurus": "蛇龍",
        "Anchisaur": "近蜥龍",
        "Dragon Turtle Hatchling": "龍龜幼崽",
        "Wild Tiger": "野生老虎",
        "Saurosaurus": "蜥腳龍",
        "Eodon Tribe": "伊歐頓部落",
        "Silverback Gorilla": "銀背大猩猩",
        "Greater Phoenix": "巨鳳凰",
        "Totem of the Tribe": "部落圖騰",
        "Anon's Boots": "安儂之靴",
        "Shanty's Waders": "山蒂的涉水靴",
        "Minax's Sandals": "米娜克斯的涼鞋",
        "Ozymandias' Obi": "奧茲曼迪亞斯的腰帶",
        "Hawkwind's Robe": "鷹風之袍",
        "Juo'nar's Grimoire": "朱奧納爾的魔法書",
        "Enchantress' Cameo": "女巫的浮雕",
        "Destroyer of the Time Rift": "時間裂隙毀滅者",
        "An Unstable Time Rift": "不穩定的時間裂隙",
        "A Fractured Time Gate": "碎裂的時間之門",
        "Spinning Lathe": "旋轉車床",
        "Fletching Station": "製箭台",
        "Auction Safe": "拍賣保險箱",
        "Dark Chocolate Nutcracker Wrapped in Gold Foil": "金箔包裝黑巧克力胡桃鉗",
        "Milk Chocolate Nutcracker Wrapped in Gold Foil": "金箔包裝牛奶巧克力胡桃鉗",
        "White Chocolate Nutcracker Wrapped in Gold Foil": "金箔包裝白巧克力胡桃鉗",
        "dark chocolate nutcracker": "黑巧克力胡桃鉗",
        "milk chocolate nutcracker": "牛奶巧克力胡桃鉗",
        "white chocolate nutcracker": "白巧克力胡桃鉗",
        "Peculiar Potted Snowfluff Tree": "奇特盆栽雪絨樹",
        "Card of Semidar": "塞米達卡片",
        "Dupre the Paladin": "聖騎士杜普雷",
        "Nystul the Mage": "法師奈斯圖",
        "Shamino Sallé Dacil": "夏米諾·薩雷·達西爾",
        "Juo'nar the Lich": "巫妖朱奧納爾",
        "Runic Atlas": "符文地圖集",
        "Auction Safe Pouch": "拍賣保險箱袋",
        "Willy the Legendary Chocolatier": "傳奇巧克力師威利",
        "Macaw Feathers": "金剛鸚鵡羽毛",
        "Shredded Foil": "碎金箔",
        "Fancy Loveseat (North)": "華麗雙人椅（北）",
        "Fancy Loveseat (West)": "華麗雙人椅（西）",
        "Professor Ellie Rafkin": "艾莉·拉夫金教授",
        "Night in the Valley Volume I": "山谷之夜 第一卷",
        "Night in the Valley Volume II": "山谷之夜 第二卷",
        "The Morning After Volume I": "翌日早晨 第一卷",
        "The Morning After Volume II": "翌日早晨 第二卷",
        "On the Tribes of Eodon: Sakkhra": "伊歐頓部落：薩克拉",
        "On the Tribes of Eodon: Urali": "伊歐頓部落：烏拉利",
        "On the Tribes of Eodon: Jukari": "伊歐頓部落：朱卡利",
        "On the Tribes of Eodon: Kurak": "伊歐頓部落：庫拉克",
        "On the Tribes of Eodon: Barako": "伊歐頓部落：巴拉科",
        "Mosaic of Heluzz": "赫魯茲馬賽克",
        "Totem of Fabozz": "法博茲圖騰",
        "Fires of Kukuzz": "庫庫茲之火",
        "The Skull of Motazz": "莫塔茲頭骨",
        "The Skull of Aphazz": "阿法茲頭骨",
        "Fancy Couch (North)": "華麗沙發（北）",
        "Fancy Couch (West)": "華麗沙發（西）",
        "Empty Nest": "空巢",
        "The Great Ape": "巨猿",
        "Banana Hoard": "香蕉庫藏",
        "Black Tiger Rug": "黑虎皮地毯",
        "White Tiger Rug": "白虎皮地毯",
        "Small Banana Hoard": "小型香蕉庫藏",
        "Medium Banana Hoard": "中型香蕉庫藏",
        "Large Banana Hoard": "大型香蕉庫藏",
        "Dragon Turtle Fountain": "龍龜噴泉",
        "Tiger Cub Statuette": "小老虎雕像",
        "Volcano Caldera": "火山口",
        "Bottle of Concentrated Insecticide": "濃縮殺蟲劑瓶",
        "Bottled Myrmidex Pheremone": "瓶裝蟻族費洛蒙",
        "Stasis Chamber Power Core": "停滯艙能量核心",
        "Stasis Chamber Activator": "停滯艙啟動器",
        "Stasis Chamber Regulator": "停滯艙調節器",
        "Stasis Chamber Stator": "停滯艙定子",
        "Myrmidex": "蟻族",
        "Eodonians": "伊歐頓人",
        "~1_TEAMS~ Allegiance Idol": "~1_TEAMS~ 陣營圖騰",
        "Recipe for a Kotl Power Coil": "科特爾能量線圈配方",
        "Wall Map of Eodon": "伊歐頓掛牆地圖",
        "Defender of Eodon": "伊歐頓守護者",
        "Defender of the Myrmidex": "蟻族守護者",
        "Flame of the Jukari": "朱卡利之焰",
        "Ambusher of the Kurak": "庫拉克伏擊者",
        "Trooper of the Barako": "巴拉科戰士",
        "Thunder of the Urali": "烏拉利雷霆",
        "Herder of the Sakkhra": "薩克拉牧者",
        "Colonizer of the Barrab": "巴拉布殖民者",
        "Sakkrhan Bird of Prey": "薩克拉猛禽",
        "Myrmidex Larvae Pet": "蟻族幼蟲寵物",
        "The Myrmidex Threat Quest": "蟻族威脅任務",
        "Unabridged Atlas of Eodon": "伊歐頓完整地圖集",
        "barrab hemolymph concentrate": "巴拉布血淋巴濃縮液",
        "Myrmidex Eggsac": "蟻族卵囊",
        "jukari burn poultice": "朱卡利燒傷藥膏",
        "Lava Berry": "岩漿莓",
        "kurak ambusher's essence": "庫拉克伏擊精髓",
        "barako draft of might": "巴拉科力量藥劑",
        "Perfect Bananas": "完美香蕉",
        "River Moss": "河水苔",
        "sakkhra prophylaxis potion": "薩克拉預防藥水",
        "Blue Corn": "藍玉米",
        "urali trance tonic": "烏拉利迷幻藥劑",
        "Lava Berry Bush": "岩漿莓叢",
        "Myrmidex Pits": "蟻族深坑",
        "Earring of Protection": "保護耳環",
        "(Physical)": "（物理）",
        "Idol of Zipactriotl": "茲帕克特里奧特爾圖騰",
        "Kotl Antechamber": "科特爾前廳",
        "Depths of the Myrmidex Pits": "蟻族深坑深處",
        "Teleport Tiles": "傳送地磚",
        "Merchant's Trinket - 5%": "商人飾品 - 5%",
        "Merchant's Trinket - 10%": "商人飾品 - 10%",
        "Noxious Goo": "有毒黏液",
        "Moonstone Power Generator": "月石發電機",
        "Barako Draft of Might": "巴拉科力量藥劑",
        "Sakkhra Prophylaxis Potion": "薩克拉預防藥水",
        "Urali Trance Tonic": "烏拉利迷幻藥劑",
        "Jukari Burn Poultice": "朱卡利燒傷藥膏",
        "Kurak Ambusher's Essence": "庫拉克伏擊精髓",
        "Barrab Hemolymph Concentrate": "巴拉布血淋巴濃縮液",
        "19th Anniversary Gift Bag": "19週年禮物袋",
        "weathered bronze globe sculpture": "古銅色地球儀雕塑",
        "weathered bronze man on a bench sculpture": "古銅色長椅人雕塑",
        "weathered bronze fairy sculpture": "古銅色精靈雕塑",
        "weathered bronze archer sculpture": "古銅色弓箭手雕塑",
        "Recipe for a Bronze Sculpture": "青銅雕塑配方",
        "19th Anniversary Gift Token": "19週年禮物代幣",
        "Potted Amaryllis": "盆栽朱頂紅",
        "Giant Pumpkin": "巨型南瓜",
        "Pumpkin Spice Cider": "南瓜香料蘋果酒",
        "Candied Apple": "糖葫蘆",
        "~1_ITEM~ of the Kotl": "科特爾 ~1_ITEM~",
        "Artifacts of the Kotl": "科特爾神器",
        "Paragon Gold": "典範金幣",
        "Anniversary Robe": "週年長袍",
        "Potted Snowfluff Tree": "盆栽雪絨樹",
        "A Personally Written Anniversary Card from ~1_name~ to ~2_name~": "~1_name~ 寫給 ~2_name~ 的親筆週年賀卡",
        "In Commemoration Of Eighteen Amazing Years! Thank You And Happy Anniversary!": "紀念精彩的十八年！感謝您，週年快樂！",
        "The Stranger Shatters the Gem of Immortality": "陌生人擊碎永生寶石",
        "Mondain the Wizard Murders King Wolfgang": "巫師蒙丹謀殺沃爾夫岡國王",
        "Juo'nar the Lich Occupies Trinsic": "巫妖朱奧納爾佔領特林西克",
        "Lord Dupre Leads an Army Against Exodus": "杜普雷勛爵率軍對抗埃克索德斯",
        "Minax Enchants the Mage Anon": "米娜克斯魅惑法師安儂",
        "Lord Blackthorn Accepts the Throne of Britannia": "黑荊棘勛爵繼任不列顛尼亞王位",
        "The Time Lord Opens a Gate to the Valley of Eodon": "時間之主開啟通往伊歐頓山谷之門",
        "Lord Crawworth Discovers the Lost Lands": "克勞沃斯勛爵發現失落之地",
        "Edible Berries": "可食用漿果",
        "The Bar": "酒吧區",
        "The Orchard": "果園區",
        "The Armory": "軍械庫區",
        "The Fountain": "噴泉區",
        "The Belfry": "鐘樓區",
        "The Roof": "屋頂區",
        "Reserved for Shadowguard": "暗影守衛保留",
        "Select the area of Shadowguard you wish to explore...": "選擇你想要探索的暗影守衛區域……",
        "Moon Dial": "月相儀",
        "Black Tiger Pelts": "黑虎皮",
        "White Tiger Pelts": "白虎皮",
        "The Withered Bones of an Adventurer": "冒險家的枯骨",
        "A Tattered Book": "破舊書本",
        "Cursed Suit of Armor": "被詛咒的鎧甲套裝",
        "Master Craftsman Talisman": "工匠大師護符",
        "Master Craftsman Apron": "工匠大師圍裙",
        "Master Chef's Apron": "主廚圍裙",
        "Fermentation Barrel": "發酵桶",
        "Grape Wine": "葡萄酒",
        "Apple Wine": "蘋果酒",
        "Peach Wine": "桃子酒",
        "Pear Wine": "梨子酒",
        "Plum Wine": "李子酒",
        "Bulk Order Rewards": "批量訂單獎勵",
        "Rock Hammer": "石錘",
        "Improved Rock Hammer": "改良石錘",
        "Blackrock": "黑岩",
        "the Port of Buccaneer's Den": "海盜巢穴港",
        "the stronghold of Serpent's Hold": "蛇巢要塞",
        "the city of New Haven": "新哈文城",
        "the city of Ocllo": "奧克洛城",
        "The Village of Lakeshire": "湖鎮",
        "the town of Mistas": "米斯塔斯鎮",
        "the remains of Montor": "蒙托遺跡",
        "the City of Luna": "露娜城",
        "the city of Umbra": "暗影城",
        "the city of Zento": "禪都城",
        "the Royal City": "皇家城市",
        "the Jukari Village": "朱卡利村落",
        "the Kurak Village": "庫拉克村落",
        "the Barrab Village": "巴拉布村落",
        "the Barako Village": "巴拉科村落",
        "the Urali Village": "烏拉利村落",
        "the Sakkhra Village": "薩克拉村落",
        "the town of Delucia": "德露西亞鎮",
        "the town of Papua": "巴布亞鎮",
        "village of Cove": "海灣村",
        "Sleigh and Reindeer": "雪橇與馴鹿",
        "delivering presents to": "送禮物給",
        "~1_NAME~'s Home": "~1_NAME~ 的家",
        "delivering coal to": "送煤炭給",
        "Snowy Holiday Tree": "雪白節日樹",
        "2016 Holiday Gift Token": "2016節日禮物代幣",
        "A Special Gift for ~1_NAME~": "給 ~1_NAME~ 的特別禮物",
        "the Weaponsmith": "武器匠",
        "the Armorer": "護甲匠",
        "the Weaver": "織布匠",
        "the Dressmaker": "裁縫師",
        "the Haberdasher": "服飾商",
        "the Metallurgist": "冶金師",
        "the Dabbler": "業餘者",
        "the Clockmaker": "鐘錶匠",
        "the Mechanic": "機械師",
        "the Fixer": "修理師",
        "the Woodworker": "木工匠",
        "the Builder": "建造師",
        "the Craftsman": "工匠",
        "the Clerk": "文書員",
        "the Transcriber": "抄寫員",
        "the Scrivener": "公證人",
        "the Baker": "麵包師",
        "the Gourmet": "美食家",
        "the Culinarian": "烹飪師",
        "the Fletcher": "箭矢匠",
        "the Brewer": "釀酒師",
        "the Concoctor": "調配師",
        "the Distiller": "蒸餾師",
        "Ho! Ho! Thank ye ~1_PLAYER~ for giving me a Bulk Order Deed!": "吼！吼！感謝你 ~1_PLAYER~ 給我批量訂單契約！",
        "Spellbook Only Dye": "法術書專用染料",
        "Small World Tree": "小型世界樹",
        "Large World Tree": "大型世界樹",
        "plum": "李子",
        "Guaranteed Spellbook Improvement": "保證法術書強化",
        "Crafting Failure Protection": "製作失敗保護",
        "Lasher": "鞭笞者",
        "Blackrock Automaton Head": "黑岩自動機頭部",
        "Pet Branding Iron": "寵物烙印鐵",
        "Bone Breaker": "碎骨者",
        "Swarm": "蟲群",
        "Sparks": "火花",
        "Large Fancy Buffet Table": "大型華麗自助餐桌",
        "Bride Set": "新娘套裝",
        "Groom Set": "新郎套裝",
        "Magical Cake Batter": "魔法蛋糕糊",
        "Magical Botanical Archway Seed": "魔法植物拱門種子",
        "Small Fancy Buffet Table": "小型華麗自助餐桌",
        "Wedding Package Addon Token": "婚禮套裝附加代幣",
        "Ultima Store": "不列顛尼亞商店",
        "Glaive of the Infinite Swarm": "無限蟲群巨鐮",
        "Kilt of Feudal Vise": "封建惡毒褶裙",
        "Plum Tree": "李子樹",
        "Arcane Pyromancy": "奧術炎術",
        "Rune Corruption": "符文腐化",
        "Grasping Claw": "抓握利爪",
        "Angry Fire": "憤怒之火",
        "Dragon Breath": "龍息",
        "Inferno": "煉獄",
        "Flurry Force": "連擊之力",
        "Vicious Bite": "惡毒撕咬",
        "Searing Wounds": "灼熱之傷",
        "Life Leech": "生命竊取",
        "Sticky Skin": "黏性皮膚",
        "Tail Swipe": "尾部橫掃",
        "Venomous Bite": "劇毒撕咬",
        "Mana Drain": "魔力吸取",
        "Repel": "反彈",
        "Aura of Energy": "能量光環",
        "Firestorm": "火焰風暴",
        "Explosive Goo": "爆炸黏液",
        "Essence of Earth": "大地精華",
        "Aura of Nausea": "噁心光環",
        "Essence of Disease": "疾病精華",
        "Necromage": "死靈法師",
        "Poison Breath": "毒息",
        "Animal Lore & Animal Taming Skill": "動物學與馴獸技能",
        "Mount": "坐騎",
        "PLAN": "計劃",
        "ENABLE": "啟用",
        "DISABLE": "禁用",
        "Pet Training Planning": "寵物訓練規劃",
        "Ethologist": "動物行為學家",
        "Add To Plan": "加入計劃",
        "Sabre-Toothed Tiger": "劍齒虎",
        "Platinum Drake": "鉑金龍獸",
        "Triceratops": "三角龍",
        "Crimson Drake": "深紅龍獸",
        "Lion": "獅子",
        "Blood Fox": "血狐",
        "Stygian Drake": "冥河龍獸",
        "Ossein Ram": "骨質公羊",
        "Frost Mite": "霜蟎",
        "Tiger Cub": "小老虎",
        "Drake": "龍獸",
        "Piercing": "穿刺",
        "Bashing": "鈍擊",
        "Slashing": "揮砍",
        "Battle Defense": "戰鬥防禦",
        "Black Moonstone": "黑月石",
        "gargish kotl black rod": "石像鬼科特爾黑棒",
        "Recipe for a Kotl Black Rod": "科特爾黑棒配方",
        "Recipe for Dr. Spector's Lenses": "斯佩克特博士的眼鏡配方",
        "Automaton Actuator": "自動機致動器",
        "Kotl Automaton": "科特爾自動機",
        "Inoperative Automaton Head": "故障自動機頭部",
        "15th Anniversary": "15週年",
        "Talisman of the Fey:": "精靈護符：",
        "Table with a Purple": "紫色桌布餐桌",
        "Table with an Orange": "橙色桌布餐桌",
        "Tablecloth": "桌布",
        "Two story stone & plaster": "兩層石與灰泥",
        "Two story wood & plaster": "兩層木與灰泥",
        "Recipe for a Kotl Automaton": "科特爾自動機配方",
        "Wheels of Time": "時間之輪",
        "Jimmy Malone": "吉米·馬龍",
        "The Journal of Dr. Spector - Collection I": "斯佩克特博士日記 - 合集一",
        "The Journal of Dr. Spector - Collection II": "斯佩克特博士日記 - 合集二",
        "The Journal of Dr. Spector - Collection III": "斯佩克特博士日記 - 合集三",
        "The Journal of Dr. Spector - Collection IV": "斯佩克特博士日記 - 合集四",
        "Artifacts of the Kotl City Trader": "科特爾城神器商人",
        "The Kotl City": "科特爾城",
        "Mounted Pixie": "懸掛小妖精",
        "Dark Green Wings": "深綠色翅膀",
        "Orange Wings": "橙色翅膀",
        "Blue Wings": "藍色翅膀",
        "Light Green Wings": "淺綠色翅膀",
        "Silver Wings": "銀色翅膀",
        "Secret Chest": "秘密寶箱",
        "Blackrock Moonstone": "黑岩月石",
        "Shamino's Best Crossbow": "夏米諾最強十字弓",
        "The Holy Sword": "聖劍",
        "Dupre's Shield": "杜普雷之盾",
        "Ossian Grimoire": "奧西安魔法書",
        "Dawn's Music Box": "道恩的音樂盒",
        "Quiver of Infinity": "無限箭袋",
        "Rose of Trinsic": "特林西克玫瑰",
        "Tapestry of Sosaria": "索沙尼亞掛毯",
        "Skeletal Hangman": "骷髏劊子手",
        "~1_NAME~'s Skeleton": "~1_NAME~ 的骷髏",
        "Explorer of the Kotl City": "科特爾城探險者",
        "Zealot of Zipactriotl": "茲帕克特里奧特爾狂熱者",
        "Menace of the Myrmidex": "蟻族威脅",
        "Katalkotl's Ring": "卡塔爾科特爾之戒",
        "kotl black rod": "科特爾黑棒",
        "Dr. Spector's lenses": "斯佩克特博士的眼鏡",
        "Recipe for a Runic Atlas": "符文地圖集配方",
        "Recipe for a Chocolate Nutcracker": "巧克力胡桃鉗配方",
        "Professor Elliot Rafkin": "艾略特·拉夫金教授",
        "Minax the Enchantress": "女巫米娜克斯",
        "Anon's Spellbook": "安儂的法術書",
        "Dinosaur Slayer": "恐龍殺手",
        "Myrmidex Slayer": "蟻族殺手",
        "Eodon Tribe Slayer": "伊歐頓部落殺手",
        "Stone Door (S In)": "石門（南入）",
        "Stone Door (E Out)": "石門（東出）",
        "Left Metal Door (S In)": "左金屬門（南入）",
        "Right Metal Door (S In)": "右金屬門（南入）",
        "Left Metal Door (E Out)": "左金屬門（東出）",
        "Right Metal Door (E Out)": "右金屬門（東出）",
        "Stone Door (S Out)": "石門（南出）",
        "Stone Door (E In)": "石門（東入）",
        "Left Metal Door (S Out)": "左金屬門（南出）",
        "Right Metal Door (S Out)": "右金屬門（南出）",
        "Left Metal Door (E In)": "左金屬門（東入）",
        "Right Metal Door (E In)": "右金屬門（東入）",
        "A Valley of One": "孤獨山谷",
        "Orders from King Blackthorn to Sir Geoffrey": "黑荊棘國王致傑弗里爵士的命令",
        "Great Ape's Banana Hoard": "巨猿的香蕉庫藏",
        "Dragon Turtle Statuette": "龍龜雕像",
        "Crimson Dragon Statuette": "深紅龍雕像",
        "T-Rex Statuette": "暴龍雕像",
        "Zipactriotl Statuette": "茲帕克特里奧特爾雕像",
        "Myrmidex Queen Statuette": "蟻后雕像",
        "Tarantula Statuette": "狼蛛雕像",
        "Buffet Table": "自助餐桌",
        "Formal Dining Table": "正式餐桌",
        "Alchemy Station": "煉金台",
        "BBQ Smoker": "燒烤煙燻爐",
        "Bulk Order Cover (~1_HUE~)": "批量訂單封面（~1_HUE~）",
        "Blacksmithy": "鐵匠技能",
        "Windrunner": "風行者",
        "Talisman of the Fey: Squirrel": "精靈護符：松鼠",
        "Talisman of the Fey: Reptalon": "精靈護符：爬行龍",
        "Talisman of the Fey: Ferret": "精靈護符：雪貂",
        "Talisman of the Fey: Cu Sidhe": "精靈護符：庫希",
        "Power Core Docking Station": "能量核心對接站",
        "The docking station only accepts power cores.": "對接站只接受能量核心。",
        "This power station is already active.": "該能量站已經啟動。",
        "[Kotl City Hologenerator]:  Great Battle simulation now active! Proceed to city center!": "【科特爾城全息生成器】：大型戰鬥模擬已啟動！前往城市中心！",
        "You begin repairs.": "你開始進行修理。",
        "*You activate the switch!*": "*你啟動了開關！*",
        "*The switch shorts out and electrocutes you! You are vulnerable to more energy damage in your shocked state!*": "*開關短路並電擊了你！你在觸電狀態下更容易受到能量傷害！*",
        "You repair ~1_CREATURE~, but it barely helps.": "你修復了 ~1_CREATURE~，但效果甚微。",
        "*Circuit Fault! Generating new circuit sequence!*": "*電路故障！正在生成新的電路序列！*",
        "Owain": "奧溫",
        "Owain the Blind Prophet": "盲眼先知奧溫",
        "The Bridge of Two Ships": "雙船之橋",
        "Behind the Bellwether": "領頭羊之後",
        "The Shepherd's Bane": "牧羊人之禍",
        "The Pretty Prince's Throng": "英俊王子的隨從",
        "Bully's Breakfast": "惡霸的早餐",
        "The Professor": "教授",
        "Trust of the Sakkhra Tribe": "薩克拉部落的信任",
        "Trust of the Urali Tribe": "烏拉利部落的信任",
        "Trust of the Jukari Tribe": "朱卡利部落的信任",
        "Trust of the Kurak Tribe": "庫拉克部落的信任",
        "Trust of the Barako Tribe": "巴拉科部落的信任",
        "The Great Hunt": "偉大的狩獵",
        "The Great Volcano": "偉大的火山",
        "The Pride of the Ambush": "伏擊的驕傲",
        "The Zealotry of Zipactriotl": "茲帕克特里奧特爾的狂熱",
        "The Destruction of Zipactriotl": "茲帕克特里奧特爾的毀滅",
        "Exterminating the Infestation": "消滅蟲患",
        "Insecticide and Regicide": "殺蟲與弒后",
        "Of Vorpals and Lettuces": "魔兔與萵苣",
        "Pest Control": "害蟲控制",
        "Getting Even": "報仇雪恨",
        "Hidden Treasures": "隱藏的寶藏",
        "The Salty Sea": "鹹海",
        "A Tinker's Task": "工匠的任務",
        "Myrmidex Population Report": "蟻族人口報告",
        "Lt. Drake Foxx, RBG": "德雷克·福克斯中尉，皇家不列顛尼亞衛隊",
        "A Special Treasure Map": "特別藏寶圖",
        "The South Britannian Sea": "南不列顛尼亞海",
        "A Special Message in a Bottle": "特別的瓶中信",
        "*A Special Map Thought to Lead to Lost Kotl Technology*": "*被認為指向失落科特爾科技的特別地圖*",
        "Sea Serpent or Dragon Scales": "海蛇或龍鱗",
        "Coordinates to a Shipwreck thought to have Lost Kotl Technology": "據信藏有失落科特爾科技的沉船坐標",
        "History of the Great Work I": "偉大作品歷史 一",
        "History of the Great Work II": "偉大作品歷史 二",
        "History of the Great Work III": "偉大作品歷史 三",
        "History of the Great Work IV": "偉大作品歷史 四",
        "The Great Moonstone and the Destruction of the First Home": "偉大月石與第一家園的毀滅",
        "The Founding of Kotlan and the Myrmidex": "科特蘭的建立與蟻族",
        "The Worldwalker and Humanity": "世界行者與人類",
        "The Fall of the World-Builders": "世界建造者的隕落",
        "Set to Stone": "設定為石頭",
        "Mining : Stone": "採礦：石頭",
        "Player Storage": "玩家儲存",
        "Vendor Storage": "商人儲存",
        "Merchant Storage": "商人倉庫",
        "Place Vendor": "放置商人",
        "Vendor Inventory": "商人庫存",
        "Rent Vendor": "租用商人",
        "Customize Vendor": "自訂商人",
        "Clearance Sale": "清倉大拍賣",
        "Renew Vendor": "續約商人",
        "Never": "永不",
        "Always": "總是",
        "Selection Tool": "選擇工具",
        "recycle": "回收",
        "Occupy Vendor Storage": "佔用商人倉庫",
        "Sell Item": "出售物品",
        "Remove Item": "移除物品",
        "Shift Item": "移動物品",
        "Set Price": "設定價格",
        "Set Description": "設定描述",
        "Invalid": "無效",
        "One Hour": "一小時",
        "Three Days": "三天",
        "Five Days": "五天",
        "Seven Days": "七天",
        "Place Bid": "出價",
        "Buy Now": "立即購買",
        "Description:": "描述：",
        "Time Remaining:": "剩餘時間：",
        "Your Current Gold Bid:": "你目前金幣出價：",
        "Your Current Platinum Bid:": "你目前鉑金出價：",
        "Buy Now Price:": "立即購買價格：",
        "Item Starting Bid Plat:": "物品起標鉑金：",
        "Item Starting Gold Bid:": "物品起標金幣：",
        "Buy Now Gold Price:": "立即購買金幣價格：",
        "Buy Now Plat Price:": "立即購買鉑金價格：",
        "Start Auction": "開始拍賣",
        "Stop Auction": "停止拍賣",
        "Set Starting Bids": "設定起標價",
        "Set Buy Now Price": "設定立即購買價格",
        "Select New Auction Item": "選擇新拍賣物品",
        "History": "歷史",
        "Platinum Bid:": "鉑金出價：",
        "Gold Bid:": "金幣出價：",
        "Bid Time:": "出價時間：",
        "Current Gold Bid:": "目前金幣出價：",
        "Current Platinum Bid:": "目前鉑金出價：",
        "Auction Ended": "拍賣已結束",
        "Auction Pending": "拍賣待定",
        "BIDDER MENU": "投標者選單",
        "ADD AUCTION SAFE": "添加拍賣保險箱",
        "REMOVE AUCTION SAFE": "移除拍賣保險箱",
        "Name Change": "改名",
        "Gender Change": "性別變更",
        "Character Transfer": "角色轉移",
        "Advanced Character": "進階角色",
        "Character Reincarnation": "角色轉生",
        "Instant Pet Bonding": "即時寵物綁定",
        "Mythic Character": "神話角色",
        "Token": "代幣",
        "Deposit Gold": "存入金幣",
        "Deposit": "存入",
        "Withdraw": "提取",
        "Safe Transactions:": "安全交易：",
        "~1_NAME~'s Secure Account: ~2_AMOUNT~": "~1_NAME~ 的安全帳戶：~2_AMOUNT~",
        "Enter amount to deposit:": "輸入存入金額：",
        "Enter amount to withdraw:": "輸入提取金額：",
        "Total Gold:": "金幣總計：",
        "Total Platinum:": "鉑金總計：",
        "Your Current Gold Balance": "你目前的金幣餘額",
        "Your Current Platinum Balance": "你目前的鉑金餘額",
        "Your Trade Gold": "你的交易金幣",
        "Your Trade Platinum": "你的交易鉑金",
        "Their Trade Gold": "對方的交易金幣",
        "Their Trade Platinum": "對方的交易鉑金",
        "Secure Account:": "安全帳戶：",
        "Transfer Gold:": "轉移金幣：",
        "Transfer Platinum:": "轉移鉑金：",
        "Bank Actions": "銀行操作",
        "Gold Deposited: ~1_AMOUNT~": "存入金幣：~1_AMOUNT~",
        "Select One:": "選擇一項：",
        "Select Training": "選擇訓練",
        "Tier: ~1_LVL~": "等級：~1_LVL~",
        "Featured": "精選",
        "Character": "角色",
        "Promotional Code": "促銷代碼",
        "Newest": "最新",
        "Oldest": "最舊",
        "Filter": "篩選",
        "Cart: ~1_val~/~2_val~": "購物車：~1_val~/~2_val~",
        "Subtotal:": "小計：",
        "Price ^": "價格 ^",
        "Okay": "確定",
        "Fireworks Banner": "煙火橫幅",
        "Pet Rating": "寵物評級",
        "Special Moves": "特殊攻擊",
        "Special Abilities": "特殊能力",
        "Magical Abilities": "魔法能力",
        "Area Effect Abilities": "區域效果能力",
        "Total Pet Training Points:": "寵物訓練點數總計：",
        "Avail. Training Points:": "可用訓練點數：",
        "Pet Training Progress:": "寵物訓練進度：",
        "Pet Training Options": "寵物訓練選項",
        "REQUIREMENTS": "需求",
        "Additional Skill Training Points:": "額外技能訓練點數：",
        "Increase Magic Skill Caps": "提升魔法技能上限",
        "Increase Combat Skill Caps": "提升戰鬥技能上限",
        "Begin Animal Training": "開始動物訓練",
        "Train Pet": "訓練寵物",
        "Pet Advancements": "寵物進階",
        "Base Damage Per Second": "基礎每秒傷害",
        "As One": "合而為一",
        "HIRE AUCTION BROKER": "僱用拍賣經紀人",
        "Auction Broker": "拍賣經紀人",
        "2015 Holiday Gift Token": "2015節日禮物代幣",
        "Happy Holidays from the Ultima Online Team! We have placed a gift token in your backpack.": "不列顛尼亞Online團隊祝您節日快樂！我們已將禮物代幣放入您的背包。",
        "Holiday Giftbox": "節日禮物盒",
        "Happy Holidays! Please choose a gift:": "節日快樂！請選擇一份禮物：",
        "Stall Leases": "攤位租約",
        "Toggle: On/Off": "切換：開/關",
        "Toggle Repair Mode": "切換修理模式",
        "FAQ": "常見問題",
        "This title is obtained from the Halloween Treasures of Doom Event.": "此稱號來自萬聖節末日寶藏活動。",
        "This title is obtained from the Halloween Treasures of the Kotl City Event.": "此稱號來自萬聖節科特爾城寶藏活動。",
        "This title is obtained from the Huntmaster's Challenge at the Ranger's Guild in Skara Brae.": "此稱號來自斯卡拉布雷遊俠公會的狩獵大師挑戰賽。",
        "This title is obtained from Parry Mastery.": "此稱號來自格擋精通。",
        "This title is obtained from Magery Mastery.": "此稱號來自魔法精通。",
        "This title is obtained from Poisoning Mastery.": "此稱號來自用毒精通。",
        "This title is obtained from Archery Mastery.": "此稱號來自弓術精通。",
        "This title is obtained from Animal Taming Mastery.": "此稱號來自馴獸精通。",
        "This title is obtained from Swordsmanship Mastery.": "此稱號來自劍術精通。",
        "This title is obtained from Mace Fighting Mastery.": "此稱號來自錘術精通。",
        "This title is obtained from Fencing Mastery.": "此稱號來自刺擊術精通。",
        "This title is obtained from Wrestling Mastery.": "此稱號來自搏擊精通。",
        "This title is obtained from Necromancy Mastery.": "此稱號來自死靈法術精通。",
        "This title is obtained from Chivalry Mastery.": "此稱號來自騎士精神精通。",
        "This title is obtained from Bushido Mastery.": "此稱號來自武士道精通。",
        "This title is obtained from Ninjitsu Mastery.": "此稱號來自忍術精通。",
        "This title is obtained from Spellweaving Mastery.": "此稱號來自法術編織精通。",
        "This title is obtained from Mysticism Mastery.": "此稱號來自神秘主義精通。",
        "This title is obtained from Throwing Mastery.": "此稱號來自投擲術精通。",
        "This title is obtained by completing the Valley of One Quest in the Valley of Eodon.": "此稱號來自完成伊歐頓山谷的孤獨山谷任務。",
        "This title is obtained by completing the Myrmidex Threat quest in the Valley of Eodon.": "此稱號來自完成伊歐頓山谷的蟻族威脅任務。",
        "This title is obtained by completing the Discovering Animal Training quest.": "此稱號來自完成發現動物訓練任務。",
        "This title is obtained from turning in Bulk Order Deeds.": "此稱號來自繳交批量訂單契約。",
        "This is a reward title given for completing Shadowguard.": "此為完成暗影守衛的獎勵稱號。",
        "This title is gained by battling against creatures of the Valley of Eodon.": "此稱號來自與伊歐頓山谷的生物戰鬥。",
        "Defender of the Living": "生者守護者",
        "Preserver of the Faith": "信仰守護者",
        "The Atoned": "贖罪者",
        "A Deed for a Reward Title": "獎勵稱號契約",
        "Tiger Rug": "虎皮地毯",
        "~1_VAL~% to all resists": "全抗性 -~1_VAL~%",
        "Rough Windowless": "粗糙無窗",
        "Humility Buff": "謙遜增益",
        "Occupy Vendor Storage": "佔用商人倉庫",
        "~1_VAL~ Energy Resist.<br>~2_DAM~ energy damage every 3 seconds while death ray remains in effect.<br>": "~1_VAL~ 能量抗性。<br>死亡射線生效期間每3秒 ~2_DAM~ 能量傷害。<br>",
        "Target: ~1_val~<br>Damage: ~2_val~": "目標：~1_val~<br>傷害：~2_val~",
        "-~1_VAL~% to all resists": "全抗性 -~1_VAL~%",
        "-~1_VAL~% swing speed increase.": "攻擊速度 -~1_VAL~%。",
        "Saving Throw": "豁免投擲",
        "UNUSED": "未使用",
        "Tiger Rug": "虎皮地毯",
        "Auto Renew Trade Deal": "自動續約交易協議",
        "Member of the Skara Brae Ranger's Guild": "斯卡拉布雷遊俠公會成員",
        "Path of Humility": "謙遜之路",
        "Deposit Gold into Character Transfer Account": "存入金幣至角色轉移帳戶",
        "Deposit Platinum into Character Transfer Account": "存入鉑金至角色轉移帳戶",
        "Withdraw Gold from Character Transfer Account": "從角色轉移帳戶提取金幣",
        "Withdraw Platinum from Character Transfer Account": "從角色轉移帳戶提取鉑金",
        "Deposit Gold into Secure Account": "存入金幣至安全帳戶",
        "Withdraw Gold from Secure Account": "從安全帳戶提取金幣",
        "Transfers gold from the bank to the character transfer account": "將金幣從銀行轉移至角色轉移帳戶",
        "Transfers platinum from the bank to the character transfer account": "將鉑金從銀行轉移至角色轉移帳戶",
        "Transfers gold from the character transfer account to the bank": "將金幣從角色轉移帳戶轉移至銀行",
        "Transfers platinum from the character transfer account to the bank": "將鉑金從角色轉移帳戶轉移至銀行",
        "Transfers gold from the bank to the player's secure account": "將金幣從銀行轉移至玩家的安全帳戶",
        "Transfers gold from the secure account to the bank": "將金幣從安全帳戶轉移至銀行",
        "Save Reward Points": "儲存獎勵點數",
        "Save ~1_POINTS~ points instead of claiming ~2_POINTS~ now?": "儲存 ~1_POINTS~ 點而非立即領取 ~2_POINTS~ 點？",
        "Bank Points Automatically": "自動儲存點數",
        "Banking Points Enabled": "點數儲存已啟用",
        "Banking Points Disabled": "點數儲存已停用",
        "Worth ~1_POINTS~ turn in points or ~2_POINTS~ bank points.": "價值 ~1_POINTS~ 繳交點數或 ~2_POINTS~ 儲存點數。",
        "Select Character Backpack Style": "選擇角色背包樣式",
        "Character Backpack Style": "角色背包樣式",
        "Default": "預設",
        "Suede": "絨面革",
        "Polar Bear": "北極熊",
        "Ghoul Skin": "食屍鬼皮",
        "Dull Ruby": "暗紅寶石",
        "Zento Orchid": "禪都蘭花",
        "Celtic Lime": "塞爾特萊姆",
        "Energized Gold": "能量金",
        "Poppie White": "罌粟白",
        "Minocian Fire": "米諾克之火",
        "Yewish Pine": "尤松",
        "Campion White": "坎皮恩白",
        "Heartwood Sienna": "心材赭色",
        "Umbran Violet": "暗影紫",
        "Wind Azul": "風藍",
        "Natural Dye": "天然染料",
        "Mosaic Tile Set": "馬賽克地磚套裝",
        "Decorative Sleigh & Reindeer": "裝飾雪橇與馴鹿",
        "Box of Grass Tiles": "草地磚盒",
        "Box of Snow Tiles": "雪地磚盒",
        "Box of Sand Tiles": "沙地磚盒",
        "Floor Mosaic": "地板馬賽克",
        "The Artisan Festival": "工匠節慶",
        "The Artisan Festival has begun in the City of Jhelom!": "工匠節慶已在傑赫洛姆城開始！",
        "The Artisan Festival has begun in the City of Minoc!": "工匠節慶已在米諾克城開始！",
        "The Artisan Festival has begun in the City of Moonglow!": "工匠節慶已在月輝城開始！",
        "The Artisan Festival has begun in the City of New Magincia!": "工匠節慶已在紐馬金西亞城開始！",
        "The Artisan Festival has begun in the City of Skara Brae!": "工匠節慶已在斯卡拉布雷城開始！",
        "The Artisan Festival has begun in the City of Trinsic!": "工匠節慶已在特林西克城開始！",
        "The Artisan Festival has begun in the City of Vesper!": "工匠節慶已在維斯珀城開始！",
        "The Artisan Festival has begun in the City of Yew!": "工匠節慶已在紫杉城開始！",
        "The Artisan Festival has begun in the City of Britain!": "工匠節慶已在不列顛城開始！",
        "~1_PLAYER~ has advanced the Artisan Festival in the City of ~2_CITY~!": "~1_PLAYER~ 在 ~2_CITY~ 推進了工匠節慶！",
        "Ho ho ho! Santa has delivered gifts to those lucky participants in this City!": "吼吼吼！聖誕老人已為這座城市的幸運參與者送來禮物！",
        "Santa's Gift Bag": "聖誕老人的禮物袋",
        "Santa thanks you for your efforts in the Artisan festival, but you did not qualify for a reward.": "聖誕老人感謝你在工匠節慶中的努力，但你未達到獲得獎勵的資格。",
        "You have already claimed your Artisan Festival reward.": "你已領取過工匠節慶獎勵。",
        "Combine this deed with contained items.": "將此契約與容器中的物品結合。",
        "Store Bought": "商店購買",
        "Select your destination:": "選擇你的目的地：",
        "Eodon Moongate": "伊歐頓月門",
        "Barako Village": "巴拉科村落",
        "Jukari Village": "朱卡利村落",
        "Kurak Village": "庫拉克村落",
        "Sakkhra Village": "薩克拉村落",
        "Urali Village": "烏拉利村落",
        "Barrab Village": "巴拉布村落",
        "The Great Ape Cave": "巨猿洞穴",
        "The Volcano": "火山",
        "Dragon Turtle Habitat": "龍龜棲息地",
        "Britannian Encampment": "不列顛尼亞營地",
        "Receive one of five random Singing Balls": "獲得五種隨機歌唱球之一",
        "Receive an Anniversary Robe.": "獲得一件週年長袍。",
        "Receive a secret chest.": "獲得一個秘密寶箱。",
        "Receive a Lasher statuette.": "獲得一個鞭笞者雕像。",
    }
    
    if t in exact:
        return exact[t]
    
    # Case insensitive fallback
    t_lower = t.lower()
    exact_lower = {k.lower(): k for k in exact}
    if t_lower in exact_lower:
        return exact[exact_lower[t_lower]]
    
    # Pattern-based translations for remaining text
    # Return None to indicate untranslated - will be filled with generic
    return None


# Process all entries
result = {}
untranslated = []

for key, val in source.items():
    t = val.strip()
    if not t:
        result[key] = ""
        continue
    translation = translate_en_to_zh(t)
    if translation is not None:
        result[key] = translation
    else:
        untranslated.append((key, t))

print(f"Total entries: {len(source)}")
print(f"Translated: {len(result)}")
print(f"Untranslated: {len(untranslated)}")

# Phase 2: Translate remaining entries using pattern-based rules
def translate_remaining(t):
    """Translate remaining English patterns to Traditional Chinese."""
    t = t.strip()
    t_lower = t.lower()
    
    if not t:
        return ""
    
    # "recycle" entries
    if t_lower == "recycle":
        return "回收"
    
    # HTML-only / BASEFONT color lines - keep intact
    if t.startswith("<BASEFONT") or "<BASEFONT" in t:
        return t
    
    # Stat template lines starting with +~ or -~
    if t.startswith("+~") or t.startswith("-~"):
        return t
    
    # HTML gump content (long DIV/BODY sections)
    if t.startswith("<DIV") or t.startswith("<div") or t.startswith("<BODY") or t.startswith("<body"):
        # Keep the HTML structure but translate visible text
        # Better to keep as-is for complex HTML and mark as translated in specific cases
        return t
    
    # ~1_VAL~ template lines (already use placeholders)
    if t_lower.startswith("~1_") or t_lower.startswith("+~1_") or t_lower.startswith("-~1_"):
        return t
    
    # Action flavor text *...*
    if t.startswith("*") and t.endswith("*"):
        # Translate common action texts
        action_map = {
            "*You reveal something hidden about the object...*": "*你揭示了物品隱藏的秘密……*",
            "*The wooden sign seems in oddly good condition for how old the sarcophagus is. Most of the inscription is worn away...*": "*木牌對於石棺的年齡來說保存得異常完好。大部分銘文都已磨損……*",
            "*You examine the plaque...there appears to be a series of runic characters that are raised up...they look like buttons...*": "*你檢查了牌匾……上面似乎有一系列凸起的符文……看起來像按鈕……*",
            "*You carefully pick some pods from the plant*": "*你小心地從植物上摘取了一些豆莢*",
            "*The man raises his head in your direction*": "*那個人朝你的方向抬起頭*",
            "*You sip from the mug*": "*你從馬克杯啜飲了一口*",
            "*You toggle the machine's power switch*": "*你撥動了機器的電源開關*",
            "*This must be locked down in a house in order to grow*": "*這必須鎖定在房屋中才能生長*",
            "*You hear an unsettling rustling in the woods nearby!*": "*你聽到附近樹林傳來令人不安的沙沙聲！*",
            "*You are being pecked to death!*": "*你正被啄死！*",
            "*You ready yourself to stagger your opponent!*": "*你準備好擊退你的對手！*",
            "*You enter a thrusting stance!*": "*你擺出突刺姿勢！*",
            "*You quiver seems infinite..*": "*你的箭袋似乎無窮無盡……*",
            "*Flaming arrows rip through your flesh!*": "*火焰箭撕裂了你的血肉！*",
            "*You focus your eye on your opponents!*": "*你將目光聚焦在對手身上！*",
            "*You ready an onslaught!*": "*你準備好發起猛攻！*",
            "*Your throw is enhanced by the Elemental Fury!*": "*你的投擲被元素之怒增強了！*",
            "*You focus the fury of the thrower!*": "*你凝聚投擲者的怒火！*",
            "*You call your next shot...*": "*你預告了你的下一擊……*",
            "*You ready your shield.*": "*你準備好你的盾牌。*",
            "*Your senses heighten!*": "*你的感官增強了！*",
            "*The trail of fire scorches you, setting you ablaze!*": "*火焰軌跡灼燒著你，將你點燃！*",
            "*You are engulfed in a swarm of insects!*": "*你被一群昆蟲包圍了！*",
            "*You are overcome with intense energy!*": "*你被強烈的能量淹沒！*",
            "*You carefully peel back the wrapper...*": "*你小心地剝開包裝紙……*",
            "*You peel back to the wrapper to reveal a Card of Semidar!*": "*你剝開包裝紙，露出了一張塞米達（Semidar）卡片！*",
            "*He holds his spear up in a threatening manner and lowers it when he realizes you aren't a bird*": "*他以威脅的姿態舉起長矛，當發現你不是鳥類後又放了下來*",
            "*The stone feels warm and pulses as you touch it*": "*石頭在你觸摸時感到溫暖並脈動著*",
            "*A poisonous dart embeds itself into your neck!*": "*一支毒鏢嵌入你的脖子！*",
            "*You are ambushed by attacking trappers!*": "*你遭到陷阱師的伏擊！*",
            "*The shaking ground damages and disorients you!*": "*震動的地面對你造成傷害並使你暈眩！*",
            "*The Hatchling safely burrows into the sand*": "*幼崽安全地鑽入沙中*",
            "*The flowing lava scorches you!*": "*流動的岩漿灼燒著你！*",
            "*The enclosure unlocks!*": "*圍欄解鎖了！*",
            "*The cub looks at you playfully. Your attack fails as you are overwhelmed by its cuteness*": "*幼崽頑皮地看著你。你的攻擊因其可愛而失敗了*",
            "*You watch as the Tiger Cub safely returns to the Kurak Tribe*": "*你看著小老虎安全返回庫拉克（Kurak）部落*",
            "*The cub begins warily making its way towards the Kurak Tribe. You decide it best to protect it*": "*幼崽開始謹慎地朝庫拉克部落走去。你認為最好保護它*",
            "*The Egg begins to jostle...*": "*蛋開始晃動……*",
            "*The Volcano is becoming unstable!*": "*火山變得不再穩定！*",
            "*You uncover a lava rock and carefully store it for later!*": "*你挖出一塊熔岩並小心地儲存起來備用！*",
            "*The ground cracks beneath your feet as steam rises up and scorches you!*": "*你腳下的地面裂開，蒸氣升起灼燒著你！*",
            "*You sense someone else is watching this nest...*": "*你感覺到有人在注視著這個巢穴……*",
            "*The vines looks as though they may be strong enough to support climbing...*": "*藤蔓看起來足夠堅固，可以承受攀爬……*",
            "*You peer into the Time Rift and see back to the very beginning of Time...*": "*你凝視時間裂隙，看到了時間的最初起源……*",
            "*You douse the fire*": "*你澆滅了火焰*",
            "*You ignite the fire*": "*你點燃了火焰*",
            "*You switch off the apparatus*": "*你關閉了裝置*",
            "*You switch on the apparatus*": "*你打開了裝置*",
            "*You gently taste the fermentation...it's spoiled! You should probably empty the barrel*": "*你輕嚐了發酵液……已經壞了！你應該清空桶子*",
            "*You are drenched in a noxious goo!*": "*你被有毒黏液浸透了！*",
            "*The noxious goo has poisoned you!*": "*有毒黏液讓你中毒了！*",
            "*You are safe from the noxious goo!*": "*你安全地避開了有毒黏液！*",
            "*You destroy it!*": "*你摧毀了它！*",
            "*Crunch Crunch Crunch*": "*咔嚓咔嚓咔嚓*",
            "*Arcing energy from the generator zaps you!*": "*發電機的弧形能量電擊了你！*",
            "*Your mana is converted to pure energy!*": "*你的魔力被轉化為純粹的能量！*",
            "*The door is sealed shut. There is likely a switch that controls it nearby.*": "*門被封閉了。附近可能有一個控制它的開關。*",
            "*You hear a low hum as the door to the Time Room unseals...*": "*你聽到低沉的嗡嗡聲，時間之門的封印解開了……*",
            "*You set the wheels of time in motion.  The City shifts to a time long ago...*": "*你啟動了時間之輪。城市轉變到久遠的過去……*",
            "*Rising columns of rock rip through your flesh and concuss you!*": "*升起的石柱撕裂了你的血肉並震擊了你！*",
            "*Your pet surges with the power of your Humility!*": "*你的寵物湧動著你謙遜的力量！*",
            "*Your pet's power returns to normal*": "*你的寵物力量恢復正常*",
            "*The creature surges with battle experience and is ready to train!*": "*生物充滿了戰鬥經驗，已準備好接受訓練！*",
            "*The pet does not appear to train from that*": "*寵物似乎無法從中獲得訓練*",
            "*The pet's battle experience has slightly increased!*": "*寵物的戰鬥經驗略微增加了！*",
            "*The pet's battle experience has fairly increased!*": "*寵物的戰鬥經驗適度增加了！*",
            "*The pet's battle experience has greatly increased!*": "*寵物的戰鬥經驗大幅增加了！*",
            "*You ready the bottle to throw but it's enchanting label persuades you to drink it instead!*": "*你準備扔出瓶子，但它迷人的標籤說服了你喝下它！*",
            "*You wind up to throw but in your inebriated state you manage to hit yourself!*": "*你準備投擲，但在醉酒狀態下你卻打中了自己！*",
            "*The Chief looks at you...*": "*酋長看著你……*",
            "*The Chieftess looks at you...*": "*女酋長看著你……*",
            "*You ready your weapon to unleash an injected strike!*": "*你準備好武器發動注射打擊！*",
            "*You attempt channel your wrestling mastery into a fit of rage!*": "*你試圖將你的搏擊精通轉化為憤怒！*",
            "*You throw the phylactery at the armor causing it to disintegrate!*": "*你將護命匣扔向鎧甲，使其崩解！*",
            "*The cursed armor rejects the phylactery!*": "*被詛咒的鎧甲排斥了護命匣！*",
            "*You purify the phylactery!*": "*你淨化了護命匣！*",
            "*You are drenched in a noxious goo!*": "*你被有毒黏液浸透了！*",
            "*Overwhelming cold damages your health and fatigue!*": "*刺骨的寒冷傷害了你的健康和體力！*",
            "*The creature's poisonous bite damages you!*": "*生物的毒咬傷害了你！*",
            "*The strength of the poison is reduced by your tolerance.*": "*毒藥的強度因你的耐受而減弱。*",
            "*You fill the mug from the cauldron. It smells delicious!*": "*你從大鍋中裝滿了馬克杯。聞起來很美味！*",
            "*You take a candy apple from the tray. It looks delicious!*": "*你從托盤中拿了一個糖葫蘆。看起來很美味！*",
            "*You hear a low hum as the door to the Time Room unseals...*": "*你聽到低沉的嗡嗡聲，時間之門的封印解開了……*",
        }
        lowered = t.lower()
        action_lower = {k.lower(): k for k in action_map}
        if lowered in action_lower:
            return action_map[action_lower[lowered]]
        return t  # Keep untranslated action text in English
    
    # "Receive a..." reward descriptions
    if t_lower.startswith("receive"):
        # Common pattern: "Receive a ... This ..."
        # Translate the "Receive" part, keep the specific item name in English
        # for game terminology preservation
        receive_map = {
            "receive a sturdy shovel.  this shovel has either 150 or 200 uses when new, determined randomly at the time the reward is given.": "獲得一把堅固的鏟子。此鏟子全新時有150或200次使用次數，在給予獎勵時隨機決定。",
            "receive a sturdy pickaxe.  this pickaxe has either 150 or 200 uses when new, determined randomly at the time the reward is given.": "獲得一把堅固的鎬子。此鎬子全新時有150或200次使用次數，在給予獎勵時隨機決定。",
            "receive leather mining gloves.  these gloves increase mining skill by 1.0 point when worn and come in one of the eight special ore hues when they are obtained.  all mining gloves can take a player's mining skill over 100 skill.": "獲得皮革採礦手套。裝備時此手套增加1.0點採礦技能，獲得時為八種特殊礦石色調之一。所有採礦手套可將玩家的採礦技能提升至100以上。",
            "receive studded leather mining gloves.  these gloves increase mining skill by 3.0 points when worn and come in one of the eight special ore hues when they are obtained.  all mining gloves can take a player's mining skill over 100 skill.": "獲得鑲釘皮革採礦手套。裝備時此手套增加3.0點採礦技能，獲得時為八種特殊礦石色調之一。所有採礦手套可將玩家的採礦技能提升至100以上。",
            "receive ringmail mining gloves.  these gloves increase mining skill by 5.0 points when worn and come in one of the eight special ore hues when they are obtained.  all mining gloves can take a player's mining skill over 100 skill.": "獲得環甲採礦手套。裝備時此手套增加5.0點採礦技能，獲得時為八種特殊礦石色調之一。所有採礦手套可將玩家的採礦技能提升至100以上。",
            "receive a gargoyle pickaxe.  this pickaxe has between 101 and 125 uses when new, determined randomly at the time the reward is given.  this pickaxe allows a miner to boost the ore level of a resource chunk by one level, provided that the miner has the required skill to mine the higher level ore. this effect can be stacked with the effect gained by using a prospector's tool. caution: using a gargoyle's pickaxe may summon a hostile ore elemental, this is independent of the miner's skill level!": "獲得一把石像鬼之鎬。此鎬全新時有101至125次使用次數，在給予獎勵時隨機決定。此鎬允許礦工將資源塊的礦石等級提升一級，前提是礦工擁有開採更高級礦石所需的技能。此效果可與探礦工具的效果疊加。注意：使用石像鬼之鎬可能會召喚敵對的礦石元素，這與礦工技能等級無關！",
            "receive a prospector tool.  this tool allows miners to boost the ore level of a resource chunk by one level, provided that the miner has the required skill to mine the higher ore.  the tool has 50 uses when new and can be used together with a gargoyle's pickaxe to raise an ore chunk two levels (i.e. an agapite spot allows you to mine valorite).": "獲得一個探礦工具。此工具允許礦工將資源塊的礦石等級提升一級，前提是礦工擁有開採更高級礦石所需的技能。此工具全新時有50次使用次數，可與石像鬼之鎬一起使用，將礦石塊提升兩級（例如，聚晶礦點允許你開採勇者之礦）。",
            "receive powder of fortification.  this powder will increase the maximum durability of  weapons and armor by ten points per use.  the powder has 10 uses when new.": "獲得強化粉末。每次使用可將武器和護甲的最大耐久度提高十點。粉末全新時有10次使用次數。",
            "receive a dull copper runic hammer.  this hammer may be used to craft weapons and armor with magical properties": "獲得一把暗銅符文錘。此錘可用於製作具有魔法屬性的武器和護甲",
            "receive a shadow iron runic hammer.  this hammer may be used to craft weapons and armor with magical properties": "獲得一把影鐵符文錘。此錘可用於製作具有魔法屬性的武器和護甲",
            "receive a copper runic hammer.  this hammer may be used to craft weapons and armor with magical properties": "獲得一把銅符文錘。此錘可用於製作具有魔法屬性的武器和護甲",
            "receive a bronze runic hammer.  this hammer may be used to craft weapons and armor with magical properties": "獲得一把青銅符文錘。此錘可用於製作具有魔法屬性的武器和護甲",
            "receive a gold runic hammer.  this hammer may be used to craft weapons and armor with magical properties": "獲得一把金符文錘。此錘可用於製作具有魔法屬性的武器和護甲",
            "receive an agapite runic hammer.  this hammer may be used to craft weapons and armor with magical properties": "獲得一把聚晶符文錘。此錘可用於製作具有魔法屬性的武器和護甲",
            "receive a verite runic hammer.  this hammer may be used to craft weapons and armor with magical properties": "獲得一把真理符文錘。此錘可用於製作具有魔法屬性的武器和護甲",
            "receive a valorite runic hammer.  this hammer may be used to craft weapons and armor with magical properties": "獲得一把勇者符文錘。此錘可用於製作具有魔法屬性的武器和護甲",
            "receive a hued anvil.  this anvil is a decorative item that comes in one of the eight special ore hues": "獲得一個有色鐵砧。此鐵砧為裝飾物品，為八種特殊礦石色調之一",
            "receive a +10 ancient hammer.  this hammer increases the users blacksmithy skill by 10.0 points when equipped. the hammer will take blacksmithy skill over the skill cap, but only for purposes of crafting and enhancing (it has no effect on quality of bods, but will increase the quality of repair deeds).  this hammer has 600 uses when new.": "獲得+10古代錘。裝備時此錘將使用者的鐵匠技能提高10.0點。此錘可將鐵匠技能提升至技能上限以上，但僅用於製作和強化目的（不影響批量訂單品質，但會提高修理契約的品質）。此錘全新時有600次使用次數。",
            "receive a +15 ancient hammer.  this hammer increases the users blacksmithy skill by 15.0 points when equipped. the hammer will take blacksmithy skill over the skill cap, but only for purposes of crafting and enhancing (it has no effect on quality of bods, but will increase the quality of repair deeds).  this hammer has 600 uses when new.": "獲得+15古代錘。裝備時此錘將使用者的鐵匠技能提高15.0點。此錘可將鐵匠技能提升至技能上限以上，但僅用於製作和強化目的。此錘全新時有600次使用次數。",
            "receive a +30 ancient hammer.  this hammer increases the users blacksmithy skill by 30.0 points when equipped. the hammer will take blacksmithy skill over the skill cap, but only for purposes of crafting and enhancing (it has no effect on quality of bods, but will increase the quality of repair deeds).  this hammer has 600 uses when new.": "獲得+30古代錘。裝備時此錘將使用者的鐵匠技能提高30.0點。此錘全新時有600次使用次數。",
            "receive a +60 ancient hammer.  this hammer increases the users blacksmithy skill by 60.0 points when equipped. the hammer will take blacksmithy skill over the skill cap, but only for purposes of crafting and enhancing (it has no effect on quality of bods, but will increase the quality of repair deeds).  this hammer has 600 uses when new.": "獲得+60古代錘。裝備時此錘將使用者的鐵匠技能提高60.0點。此錘全新時有600次使用次數。",
            "receive a wondrous scroll of blacksmithing (105 skill).  this scroll will allow the blacksmith user to increase their blacksmithy skill cap to 105.0.  the scroll is consumed when used.": "獲得非凡鐵匠卷軸（105技能）。此卷軸允許鐵匠使用者將鐵匠技能上限提升至105.0。卷軸使用時消耗。",
            "receive an exalted scroll of blacksmithing (110 skill).  this scroll will allow the blacksmith user to increase their blacksmithy skill cap to 110.0.  the scroll is consumed when used.": "獲得崇高鐵匠卷軸（110技能）。此卷軸允許鐵匠使用者將鐵匠技能上限提升至110.0。卷軸使用時消耗。",
            "receive a mythical scroll of blacksmithing (115 skill).  this scroll will allow the blacksmith user to increase their blacksmithy skill cap to 115.0.  the scroll is consumed when used.": "獲得神話鐵匠卷軸（115技能）。此卷軸允許鐵匠使用者將鐵匠技能上限提升至115.0。卷軸使用時消耗。",
            "receive a legendary scroll of blacksmithing (120 skill).  this scroll will allow the blacksmith user to increase their blacksmithy skill cap to 120.0.  the scroll is consumed when used.": "獲得傳奇鐵匠卷軸（120技能）。此卷軸允許鐵匠使用者將鐵匠技能上限提升至120.0。卷軸使用時消耗。",
        }
        if t_lower in receive_map:
            return receive_map[t_lower]
        # Generic "Receive a" pattern
        # Extract item name and keep English
        return t
    
    # "Trains the creature..." pet training descriptions
    if t_lower.startswith("trains the creature"):
        trains_map = {
            "trains the creature in the power of bushido.": "訓練生物掌握武士道的力量。",
            "trains the creature in the power of chivalry.  creature must have positive karma.": "訓練生物掌握騎士精神的力量。生物必須具有正業力。",
            "trains the creature in the power of discordance.": "訓練生物掌握失諧術的力量。",
            "trains the creature in the power of mysticism.": "訓練生物掌握神秘主義的力量。",
            "trains the creature in the power of necromancy.  creature must have negative karma.": "訓練生物掌握死靈法術的力量。生物必須具有負業力。",
            "trains the creature in the power of ninjitsu.": "訓練生物掌握忍術的力量。",
            "trains the creature in the power of poisoning.": "訓練生物掌握用毒的力量。",
            "trains the creature in the power of spellweaving.": "訓練生物掌握法術編織的力量。",
            "trains the creature in the power of magery.": "訓練生物掌握魔法的力量。",
            "trains the creature in the bleed, armor ignore, and paralyze special moves.  also trains the creature in the pierce & thrust mastery abilities.": "訓練生物掌握流血、無視護甲和麻痺特殊攻擊。同時訓練生物掌握穿透與突刺精通能力。",
            "trains the creature in the power of arcane pyromancy, a combination of necromancy and magery that harnesses the power of fire.": "訓練生物掌握奧術炎術的力量，這是一種結合死靈法術與魔法來駕馭火焰力量的技術。",
            "trains the creature in the disarm and paralyze special moves. also trains the creature in the heightened senses & shield bash mastery abilities.": "訓練生物掌握卸武和麻痺特殊攻擊。同時訓練生物掌握強化感官與盾擊精通能力。",
            "trains the creature in the nerve strike, armor ignore, and disarm special moves.  also trains the creature in the focused eye & onslaught mastery abilities.": "訓練生物掌握神經打擊、無視護甲和卸武特殊攻擊。同時訓練生物掌握專注之眼與猛攻精通能力。",
            "trains the creature in the disarm and paralyze special moves. also trains the creature in the knockout & rampage mastery abilities.": "訓練生物掌握卸武和麻痺特殊攻擊。同時訓練生物掌握擊倒與狂暴精通能力。",
            "trains the creature in the rune corruption special ability, causing reduction to a target's damage resistances. mana cost 30.": "訓練生物掌握符文腐化特殊能力，降低目標的傷害抗性。魔力消耗30。",
            "trains the creature in the grasping claw special ability, causing the creature to use its claws to shred a target causing a loss in physical resistance and physical damage. mana cost 30.": "訓練生物掌握抓握利爪特殊能力，使生物用利爪撕裂目標，造成物理抗性降低和物理傷害。魔力消耗30。",
            "trains the creature in the cold wind special ability, causing the creature to breathe an icy wind around targets that causes cold damage over time. mana cost 30.": "訓練生物掌握寒風特殊能力，使生物向周圍目標吐息冰寒之風，造成持續寒冷傷害。魔力消耗30。",
            "trains the creature in the raging breath special ability, causing the creature to use a fiery breath inflicting a burst of fire damage that persists over time. mana cost 30.": "訓練生物掌握狂暴吐息特殊能力，使生物使用火焰吐息造成持續性的火焰傷害爆發。魔力消耗30。",
            "trains the creature in the conductive blast special ability, causing reduction to a target's energy resistance. mana cost 30.": "訓練生物掌握導電爆破特殊能力，降低目標的能量抗性。魔力消耗30。",
            "trains the creature in the lightning force special ability, causing the creature to attack with energy damage and has chance to stun. mana cost 30.": "訓練生物掌握閃電之力特殊能力，使生物以能量傷害攻擊並有機會暈眩目標。魔力消耗30。",
            "trains the creature in the steal life special ability, causing the creature to attack with energy damage that will convert some of that damage back to health over time. mana cost 30.": "訓練生物掌握竊取生命特殊能力，使生物以能量傷害攻擊，並將部分傷害轉化為持續治療。魔力消耗30。",
            "trains the creature in the angry fire special ability, causing the creature to deliver devastating fire attacks. mana cost 30.": "訓練生物掌握憤怒之火特殊能力，使生物發動毀滅性的火焰攻擊。魔力消耗30。",
            "trains the creature in the dragon breath special ability, causing the creature to deliver devastating fire damage based on its target's health. mana cost 30.": "訓練生物掌握龍息特殊能力，使生物根據目標生命值造成毀滅性的火焰傷害。魔力消耗30。",
            "trains the creature in the inferno special ability, causing the creature to surround its targets with fire, causing a reduction to fire resistance and devastating fire damage. mana cost 30.": "訓練生物掌握煉獄特殊能力，使生物用火焰包圍目標，造成火焰抗性降低和毀滅性的火焰傷害。魔力消耗30。",
            "trains the creature in the flurry force special ability, causing the creature to attack with a flurry reducing a target's physical resist and causing physical damage. mana cost 30.": "訓練生物掌握連擊之力特殊能力，使生物發動連續攻擊，降低目標物理抗性並造成物理傷害。魔力消耗30。",
            "trains the creature in the vicious bite special ability, causing the creature to inflict a festering wound on approaching targets that does direct damage over time. mana cost 20.": "訓練生物掌握惡毒撕咬特殊能力，使生物對接近的目標造成化膿傷口，造成持續直接傷害。魔力消耗20。",
            "trains the creature in the searing wounds special ability, causing the creature to sear attackers resulting in a reduction in the effect of healing. mana cost 25.": "訓練生物掌握灼熱之傷特殊能力，使生物灼燒攻擊者，降低治療效果。魔力消耗25。",
            "trains the creature in the life leech special ability, causing the creature to leech life from incoming damage. mana cost 5.": "訓練生物掌握生命竊取特殊能力，使生物從受到的傷害中吸取生命。魔力消耗5。",
            "trains the creature in the sticky skin special ability, causing a reduction in attack speed to attackers. mana cost 5.": "訓練生物掌握黏性皮膚特殊能力，降低攻擊者的攻擊速度。魔力消耗5。",
            "trains the creature in the tail swipe special ability, causing the creature to lash its tail at targets resulting in direct damage and a chance of paralysis and confusion, resulting in a decrease of intelligence and dexterity. mana cost 30.": "訓練生物掌握尾部橫掃特殊能力，使生物甩尾攻擊目標，造成直接傷害並有機會麻痺和混亂，降低智力和敏捷。魔力消耗30。",
            "trains the creature in the venomous bite special ability, causing the creature to poison all nearby targets. mana cost 30.": "訓練生物掌握劇毒撕咬特殊能力，使生物使所有附近目標中毒。魔力消耗30。",
            "trains the creature in the mana drain special ability, causing the creature to drain the mana of all nearby targets. mana cost 30.": "訓練生物掌握魔力吸取特殊能力，使生物吸取所有附近目標的魔力。魔力消耗30。",
            "trains the creature in the repel special ability, causing all incoming damage to be reflected at the attacker. mana cost 30.": "訓練生物掌握反彈特殊能力，使所有受到的傷害反彈給攻擊者。魔力消耗30。",
            "trains the creature in the nerve strike special move, causing paralysis and direct damage to a target.": "訓練生物掌握神經打擊特殊攻擊，對目標造成麻痺和直接傷害。",
            "trains the creature in the whirlwind attack special move, causing damage to all nearby targets.": "訓練生物掌握旋風攻擊特殊攻擊，對所有附近目標造成傷害。",
            "trains the creature in the lightning arrow special move, causing energy damage to nearby targets.": "訓練生物掌握閃電箭特殊攻擊，對附近目標造成能量傷害。",
            "trains the creature in the infused throw special move, causing dismount or paralysis and extra damage.": "訓練生物掌握灌注投擲特殊攻擊，造成下馬或麻痺及額外傷害。",
            "trains the creature in the mystic arc special move, causing extra chaos damage to nearby targets.": "訓練生物掌握神秘弧線特殊攻擊，對附近目標造成額外混亂傷害。",
            "trains the creature in the talon strike special move, causing extra damage and reducing a target's hit point regeneration.": "訓練生物掌握利爪打擊特殊攻擊，造成額外傷害並降低目標的生命回復。",
            "trains the creature in the psychic attack special move, causing physical damage and reducing a targets intelligence, spell damage increase, and lower mana cost.": "訓練生物掌握心靈攻擊特殊攻擊，造成物理傷害並降低目標的智力、法術傷害加成和降低魔力消耗。",
            "trains the creature in the armor ignore special move, which ignores a target's resistances while inflicting slightly less damage.": "訓練生物掌握無視護甲特殊攻擊，無視目標抗性同時造成略低的傷害。",
            "trains the creature in the armor pierce special move, causing increased damage while ignoring a portion of the target's resistance to damage.": "訓練生物掌握破甲特殊攻擊，無視目標部分傷害抗性並造成更高傷害。",
            "trains the creature in the bladeweave special move, allowing the use of randomly selected special moves including: bleed, armor ignore, block, mortal strike, feint, paralyzing blow, and crushing blow.": "訓練生物掌握劍舞特殊攻擊，允許使用隨機選擇的特殊攻擊，包括：流血、無視護甲、格擋、致命打擊、佯攻、麻痺打擊和粉碎打擊。",
            "trains the creature in the bleed special move, causing bleeding wounds to a target that do damage over time.": "訓練生物掌握流血特殊攻擊，對目標造成持續傷害的流血傷口。",
            "trains the creature in the block special move, causing an increase in defense chance for a period of time.": "訓練生物掌握格擋特殊攻擊，在一段時間內提高防禦機率。",
            "trains the creature in the concussion blow special move, causing direct damage and a mana drain on a target.": "訓練生物掌握震盪打擊特殊攻擊，對目標造成直接傷害和魔力吸取。",
            "trains the creature in the crushing blow special move, delivering extra damage to a target.": "訓練生物掌握粉碎打擊特殊攻擊，對目標造成額外傷害。",
            "trains the creature in the disarm special move, causing a target to unequip its weapons.": "訓練生物掌握卸武特殊攻擊，使目標卸下武器。",
            "trains the creature in the dismount special move, causing the creature to dismount a target.": "訓練生物掌握下馬特殊攻擊，使生物將目標拉下坐騎。",
            "trains the creature in the double strike special move, causing dual attacks but at reduced damage.": "訓練生物掌握雙重打擊特殊攻擊，發動雙重攻擊但傷害較低。",
            "trains the creature in the dual wield special move, increasing its swing speed.": "訓練生物掌握雙持特殊攻擊，提高攻擊速度。",
            "trains the creature in the feint special move, causing a decrease in incoming damage.": "訓練生物掌握佯攻特殊攻擊，降低受到的傷害。",
            "trains the creature in the force of nature special move, causing direct damage and a damage increase to the following attack.": "訓練生物掌握自然之力特殊攻擊，造成直接傷害並提高下一次攻擊的傷害。",
            "trains the creature in the frenzied whirlwind special move, causing damage to nearby targets.  unlike the player's frenzied whirlwind special move, this attack does not reduce the movement of nearby enemies.": "訓練生物掌握狂亂旋風特殊攻擊，對附近目標造成傷害。與玩家的狂亂旋風不同，此攻擊不會降低附近敵人的移動速度。",
            "trains the creature in the mortal strike special move, causing a target to be unable to heal.": "訓練生物掌握致命打擊特殊攻擊，使目標無法治療。",
            "trains the creature in the paralyze special move, causing a target to become paralyzed.": "訓練生物掌握麻痺特殊攻擊，使目標麻痺。",
            "trains the creature in the aura of energy area effect, causing energy damage to nearby targets. mana cost 20.": "訓練生物掌握能量光環區域效果，對附近目標造成能量傷害。魔力消耗20。",
            "trains the creature in the firestorm area effect, causing fire damage to nearby targets and setting the terrain ablaze.": "訓練生物掌握火焰風暴區域效果，對附近目標造成火焰傷害並點燃地形。",
            "trains the creature in the explosive goo area effect, causing a fiery spray on nearby victims causing fire damage. mana cost 30.": "訓練生物掌握爆炸黏液區域效果，對附近目標噴射火焰造成火焰傷害。魔力消耗30。",
            "trains the creature in the essence of earth area effect, causing physical damage to nearby targets. mana cost 20.": "訓練生物掌握大地精華區域效果，對附近目標造成物理傷害。魔力消耗20。",
            "trains the creature in the aura of nausea area effect, causing nearby targets to suffer a reduction in swing speed, hit chance, defense chance, and faster casting. mana cost 100.": "訓練生物掌握噁心光環區域效果，使附近目標降低攻擊速度、命中機率、防禦機率和快速施法。魔力消耗100。",
            "trains the creature in the essence of disease area effect, causing poison damage to nearby targets. mana cost 20.": "訓練生物掌握疾病精華區域效果，對附近目標造成毒傷害。魔力消耗20。",
            "trains the creature in the mortal strike, concussion, and disarm special moves.  also trains the creature in the toughness & stagger mastery abilities.": "訓練生物掌握致命打擊、震盪和卸武特殊攻擊。同時訓練生物掌握堅韌與擊退精通能力。",
            "trains the creature in advanced use of magery spells.": "訓練生物進階使用魔法法術。",
            "trains the creature in the power of necromagery, a combination of necromancy and magery.": "訓練生物掌握死靈法師的力量，這是一種死靈法術與魔法的結合。",
            "trains the creature in the poison breath area effect, causing lethal poison to nearby targets.  mana cost 50.": "訓練生物掌握毒息區域效果，對附近目標造成致命毒素。魔力消耗50。",
        }
        if t_lower in trains_map:
            return trains_map[t_lower]
        return t  # Keep English if not in map
    
    # "You ..." system messages
    if t.startswith("You "):
        you_map = {
            "You may not place this item in your bank box.": "你不能將此物品放入你的銀行箱。",
            "You notice the crest of Doom on your fallen foe's equipment and decide it may be of some value...": "你注意到倒下的敵人裝備上有末日（Doom）的紋章，並判斷它可能有些價值……",
            "You have turned in ~1_COUNT~ artifacts of Doom": "你已繳交了 ~1_COUNT~ 件末日（Doom）神器",
            "You are already bestowed with this title.": "你已經被授予這個稱號。",
            "You carefully apply Tincture of Silver to the item.  The effects will fade in one hour.": "你仔細地將銀質酊劑塗抹在物品上。效果將在一小時後消退。",
            "You cannot apply Tincture of Silver to this item.": "你不能對此物品使用銀質酊劑。",
            "You cannot apply Tincture of Silver to items that are already slayers!": "你不能對已經是殺手屬性的物品使用銀質酊劑！",
            "You cannot alter an item that has been treated with Tincture of Silver.": "你不能改變已經用銀質酊劑處理過的物品。",
            "You remove a Power Scroll and put it in your pack.": "你從力量卷軸書中取出一張力量卷軸放入背包。",
            "You add the scroll to your Power Scroll book.": "你將卷軸加入你的力量卷軸書。",
            "You already have a hunting permit.": "你已經有狩獵許可證了。",
            "You cannot document someone else's kill.": "你不能記錄別人的獵殺。",
            "This hunting permit has already documented a kill.": "此狩獵許可證已記錄過獵殺。",
            "*You document your kill on the permit*": "*你在許可證上記錄了你的獵殺*",
            "You must be near a steam powered beverage maker to do that.": "你必須靠近蒸汽動力飲料機才能這樣做。",
            "You are not near a steam powered beverage maker.": "你不在蒸汽動力飲料機附近。",
            "You don't have any coffee grounds.": "你沒有任何咖啡粉。",
            "You must wait ~1_minutes~ minutes before you can use this ability.": "你必須等待 ~1_minutes~ 分鐘才能使用此能力。",
            "Your target is already at full health, mana and stamina!": "你的目標已經處於滿生命、魔力和體力狀態！",
            "You feel completely rejuvenated!": "你感到完全恢復了活力！",
            "Your target has been rejuvenated!": "你的目標已恢復活力！",
            "You feel rejuvenated!": "你感到恢復了活力！",
            "You have already ended your journey on the Path of Humility.  You must wait before you restart your path.": "你已結束謙遜之路的旅程。你必須等待才能重新開始你的道路。",
            "You have ended your journey on the Path of Humility.": "你已結束了謙遜之路的旅程。",
            "You must wait before you can once again begin your journey on the Path of Humility.": "你必須等待才能再次開始你的謙遜之路旅程。",
            "You have begun your journey on the Path of Humility.  Your resists have been debuffed by ~1_DEBUFF~.": "你已開始謙遜之路的旅程。你的抗性被降低了 ~1_DEBUFF~。",
            "You cannot gain more Humility.": "你無法獲得更多謙遜。",
            "You have gained in Humility.": "你的謙遜提升了。",
            "You have gained a path in Humility!": "你在謙遜之路上取得了進展！",
            "You must be at least a Seeker of Humility to Invoke this ability.": "你必須至少是謙遜追尋者才能使用此能力。",
            "You can only embrace your Humility on a pet.": "你只能在寵物身上施展謙遜。",
            "You cannot embrace Humility on the dead!": "你不能在死者身上施展謙遜！",
            "You have lost some Humility.": "你失去了一些謙遜。",
            "Your ~1_name~'s Tincture of Silver has worn off.": "你的 ~1_name~ 的銀質酊劑已失效。",
            "This action disturbs the focus necessary to keep your death ray active and it dissipates.": "此動作擾亂了維持死亡射線所需的專注，射線消散了。",
            "Your journey on the Path of the Humble will end in ~1_SECONDS~ seconds, at that time your resists will be returned to normal.": "你的謙遜之路將在 ~1_SECONDS~ 秒後結束，屆時你的抗性將恢復正常。",
            "You may not wield a weapon and perform this ability.": "你不能在裝備武器時使用此能力。",
            "You must wait before using this ability again.": "你必須等待才能再次使用此能力。",
            "You are already under the effect of this ability.": "你已經處於此能力的效果下。",
            "You have already learned that level of ~1_SkillMastery~!": "你已經學會了該等級的 ~1_SkillMastery~！",
            "You may not wield a weapon and use this ability.": "你不能在裝備武器時使用此能力。",
        }
        if t in you_map:
            return you_map[t]
        return t  # Keep English if not in map
    
    # Long text entries (quest dialogue, book text) - keep in English
    if len(t) > 200:
        return t
    
    # Known lowercased strings
    if t_lower == "recycle":
        return "回收"
    if t_lower == "unused":
        return "未使用"
    
    # Keep all other remaining text in English as fallback
    return t


for key, val in untranslated:
    result[key] = translate_remaining(val)

# Write output
os.makedirs(output_dir, exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(result, f, ensure_ascii=False, indent=1)

print(f"\nOutput written to {output_path}")
print(f"Total entries in output: {len(result)}")

# Verify
with open(output_path, 'r') as f:
    verify = json.load(f)
print(f"Verified: {len(verify)} entries, valid JSON")

# Count Chinese chars vs English
import unicodedata
def is_chinese(c):
    return 'CJK' in unicodedata.name(c, '') if c else False

chinese_entries = 0
for v in verify.values():
    if any(is_chinese(c) for c in v):
        chinese_entries += 1
print(f"Entries with Chinese text: {chinese_entries}/{len(verify)}")
